const glosary=[
    {word:"Acceptance criteria", explain:"Conditions that a system must meet to be accepted by a user or stakeholders.", phonetic:"[əkˈseptənts kraɪˈtɪərɪə]"},
    {word:"Acceptance tests", explain:"Confirm that system meets user requirements before final deployment.", phonetic:"[əkˈseptənts ˈtest]"},
    {word:"Access Control", explain:"Managing and regulating access to resources or systems.", phonetic:"[ˈækses kənˈtrəʊl]"},
    {word:"Acts", explain:"Individual commands in a script or program.", phonetic:"[ˈækts]"},
    {word:"Adaptive design", explain:"Adjusts website layout to different screen sizes.", phonetic:"[əˈdæp.tɪv dɪˈzaɪn]"},
    {word:"Adjustment", explain:"A minor change made to a system or process / Small change to system or process.", phonetic:"[əˈdʒʌst.mənt]"},
    {word:"Agile methodology", explain:"An iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˌmeθ.əˈdɒl.ə.dʒi]"},
    {word:"Agile software development", explain:"Iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˈsɒft.weər dɪˈvel.əp.mənt]"},
    {word:"AI", explain:"Artificial Intelligence, a branch of computer science that seeks to create intelligent systems.", phonetic:"[ˌeɪˈaɪ]"},
    {word:"AJAX", explain:"Technique for asynchronous web page updates.", phonetic:"[ˈeɪʤæks]"},
    {word:"Algorithm", explain:"Set of instructions for solving a problem.", phonetic:"[ˈæl.ɡə.rɪ.ðəm]"},
    {word:"Algorithmic solution", explain:"A set of step-by-step instructions to solve a specific problem.", phonetic:"[ˌæl.ɡəˈrɪð.mɪk səˈluː.ʃən]"},
    {word:"Analysis", explain:"The process of examining and breaking down a complex system or problem into smaller parts to understand its components and relationships.", phonetic:"[əˈnæl.ə.sɪs]"},
    {word:"Android", explain:"Mobile operating system developed by Google.", phonetic:"[ˈæn.drɔɪd]"},
    {word:"API integration", explain:"Connecting different software components to enable communication.", phonetic:"[ˌeɪ.piˈaɪ ˌɪn.tɪˈɡreɪ.ʃən]"},
    {word:"API", explain:"Interface for software components to interact. ", phonetic:"[ˌeɪ.piˈaɪ]"},
    {word:"Architecture", explain:"The high-level structure or design of a system, defining its components and their interactions to achieve specific objectives", phonetic:"[ˈɑː.kɪ.tek.tʃər]"},
    {word:"ASCII", explain:"Code that numerically represents a character, such as 'a' or '@.'.", phonetic:"[ˈæs.ki]"},
    {word:"Asynchronouns", explain:"A technique where tasks operate independently and don't wait for each other to complete.", phonetic:"[eɪˈsɪŋkrənəs]"},
    {word:"Authentication", explain:"Verifying the identity of a user or system to ensure secure access.", phonetic:"[ɔːˌθen.tɪˈkeɪ.ʃən]"},
    {word:"Authorization", explain:"Granting appropriate access rights to users or systems based on their authenticated identity.", phonetic:"[ˌɔː.θər.aɪˈzeɪ.ʃən]"},
    {word:"Automated test", explain:"Test run automatically by software.", phonetic:"[ˈɔː.tə.meɪ.tɪd ˈtest]"},

    {word:"Backdoor", explain:"Unauthorized access point to a system. ", phonetic:"[ˈbæk.dɔːr]"},
    {word:"Backend Development", explain:"Writing server-side logic and handling database interactions to support the functionality of a software application.", phonetic:"[ˌbæk.end dɪˈvel.əp.mənt]"},
    {word:"Backup", explain:"Copy of data used for recovery in case of loss.", phonetic:"[ˌˈbæk.ʌp]"},
    {word:"Bandwidth", explain:"Amount of data transferrable in a given time. ", phonetic:"[ˈbænd.wɪtθ]"},
    {word:"Batch", explain:"It is a file that chains commands that are carried out by the PC when it is invoked.", phonetic:"[bætʃ]"},
    {word:"BCC", explain:"BCC is the acronym for 'Blind Carbon Copy'.", phonetic:"[ˌbiːsiːˈsiː]"},
    {word:"Benchmarking", explain:"Comparing performance of different systems or software. ", phonetic:"[ˈbentʃˌmɑː.kɪŋ]"},
    {word:"Big data analytics", explain:"Analyzing large and complex datasets for insights.", phonetic:"[bɪɡ ˈdeɪ.tə ˌæn.əlˈɪt.ɪks]"},
    {word:"Big data", explain:"Large and complex datasets requiring specialized processing. ", phonetic:"[bɪɡ ˈdeɪ.tə]"},
    {word:"Binary code", explain:"Machine-readable code using 0s and 1s. ", phonetic:"[ˈbaɪ.nər.i kəʊd]"},
    {word:"Binary digit (Bit)", explain:"The smallest unit of data storage, either 0 or 1.", phonetic:"[ˈbaɪ.nər.i ˈdɪdʒ.ɪt]"},
    {word:"Binary large object (BLOB)", explain:"Storing data without a specific format.", phonetic:"[ˈbaɪ.nər.i lɑːdʒ ˈɒb.dʒɪkt]"},
    {word:"Binary representation", explain:"Binary representation is a way of representing data using only two states or values: 0s and 1s. It is used by computers and other digital systems to encapsulate and manipulate numerical values.", phonetic:"[ˈbaɪ.nər.i ˌrep.rɪ.zenˈteɪ.ʃən]"},
    {word:"BIOS initialization", explain:"Basic Input/Output System starting hardware during computer startup.", phonetic:"[ˈbaɪ.ɒs ɪˈnɪʃ.əl.aɪz]"},
    {word:"BIOS", explain:"Basic input/output system, initializes hardware during startup.", phonetic:"[ˈbaɪ.ɒs]"},
    {word:"Bitbucket", explain:"Software development platform similar to GitHub.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"BLOB", explain:"Binary large object, data stored without specific format.", phonetic:"[blɒb]"},
    {word:"Blockchain technology", explain:"A secure digital ledger using cryptographic techniques.", phonetic:"[ˈblɒk.tʃeɪn tekˈnɒl.ə.dʒi]"},
    {word:"Blockchain", explain:"Digital ledger of transactions secured through cryptography.", phonetic:"[ˈblɒk.tʃeɪn]"},
    {word:"Boot", explain:"Starting up a computer or device.", phonetic:"[buːt]"},
    {word:"Bootstrap", explain:"Front-end framework for web development. ", phonetic:"[ˈbuːt.stræp]"},
    {word:"Bootstrapping", explain:"Self-starting a computer or device. ", phonetic:"[ˈbuːtˌstræpɪŋ]"},
    {word:"Botnet network", explain:"A network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net ˈnet.wɜːk]"},
    {word:"Botnet", explain:"Network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net]"},
    {word:"Branch", explain:"Different versions of code within a single project.", phonetic:"[brɑːntʃ]"},
    {word:"Breakpoint", explain:"Pause execution of program to debug.", phonetic:"[ˈbreɪkpɔɪnt]"},
    {word:"Browser", explain:"Software used to access websites.", phonetic:"[ˈbraʊ.zər]"},
    {word:"Bug", explain:"Error in software code causing issues.", phonetic:"[bʌɡ]"},
    {word:"Business analysis", explain:"Analyzing business needs and translating them into technical requirements.", phonetic:"[ˈbɪz.nɪs əˈnæl.ə.sɪs]"},
    {word:"Business continuity", explain:"Planning and processes to ensure that critical business functions can continue in the face of disruptions.", phonetic:"[ˈbɪz.nɪs ˌkɒn.tɪˈnjuː.ə.ti]"},
    {word:"Byte storage", explain:"The basic unit of information in computer storage and processing. A byte consists of 8 adjacent binary digits (bits), each of which consists of a 0 or 1.", phonetic:"[baɪt ˈstɔː.rɪdʒ]"},
    {word:"Byte", explain:"Group of 8 bits, basic unit of memory and storage.", phonetic:"[baɪt]"},
    
    {word:"C#", explain:"Object-oriented programming language developed by Microsoft.", phonetic:"[siː] /chart/"},
    {word:"C", explain:"General-purpose programming language.", phonetic:"[siː]"},
    {word:"C++", explain:"General-purpose programming language based on C.", phonetic:"[siː] /plus plus/"},
    {word:"Cache", explain:"Copy that a computer maintains of the recently visited web pages, if the user requests them, they are read from the hard drive without having to connect to the network again; thus, achieving a very noticeable improvement in speed.", phonetic:"[kæʃ]"},
    {word:"Captcha", explain:"Completely Automated Public Turing, or Completely Automated Public Turing. It is a small test that helps determine whether a user is a computer or a human.", phonetic:"[ˈkæp.tʃə]"},
    {word:"Carriers", explain:"Telecommunications operators who own the Internet backbone networks and are responsible for data transport.", phonetic:"[ˈkær.i.ərs]"},
    {word:"Cascading Style Sheets (CSS)", explain:"Defines the visual style of web pages.", phonetic:"[ˌsiː.esˈes] or [kæsˌkeɪ.dɪŋ ˈstaɪl ˌʃiːt]"},
    {word:"CD", explain:"Compact disc for storing data.", phonetic:"[ˌsiːˈdiː]"},
    {word:"CD-RW", explain:"Rewritable compact disc, which can be written, erased and rewritten over.", phonetic:"[ˌsiː.diː.ɑːˈdʌb.əl.juː]"},
    {word:"Central processing unit (CPU)", explain:"The main brain of a computer.", phonetic:"[ˈsen.trəl ˈprəʊ.ses.ɪŋ ˈjuː.nɪt]"},
    {word:"Client-Side Scripting", explain:"Executing scripts on the user's browser to enhance interactivity.", phonetic:"[ˈklaɪ.ənt-saɪd skrɪp.tɪŋ]"},
    {word:"Cloud computing", explain:"Accessing services over the internet instead of locally.", phonetic:"[klaʊd kəmˈpjuː.tɪŋ]"},
    {word:"Cloud service", explain:"Services accessed over the internet instead of being hosted locally.", phonetic:"[klaʊd ˈsɜː.vɪs]"},
    {word:"Cluster", explain:"Hard drive storage unit. ", phonetic:"[ˈklʌs.tər]"},
    {word:"Code branching", explain:"Creating different versions of code within a single project.", phonetic:"[kəʊd brɑːnt.ʃɪŋ]"},
    {word:"Code compilation", explain:"Translating programming code into machine-readable instructions.", phonetic:"[kəʊd ˌkɒm.pɪˈleɪ.ʃən]"},
    {word:"Code declaration", explain:"Specifying a variable, function, or other entity in code.", phonetic:"[kəʊd ˌdek.ləˈreɪ.ʃən]"},
    {word:"Code refactoring", explain:"Restructuring existing code to improve its readability, maintainability, and efficiency.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"Code review", explain:"The systematic examination of source code to find and fix issues, ensure quality, and share knowledge among team members.", phonetic:"[kəʊd rɪˈvjuː]"},
    {word:"Code smells", explain:"Indicators of potential issues in code, suggesting the need for refactoring.", phonetic:"[kəʊd smels]"},
    {word:"Code ", explain:"Set of instructions for a computer to execute.", phonetic:"[kəʊd]"},
    {word:"Command execution ", explain:"Issuing instructions to a system or program.", phonetic:"[kəˈmɑːnd ˌek.sɪˈkjuː.ʃən]"},
    {word:"Command", explain:"Instruction given to a system or program. ", phonetic:"[kəˈmɑːnd]"},
    {word:"Commit", explain:"Submitting changes to a version control system like Git. ", phonetic:"[kəˈmɪt]"},
    {word:"Compact disc storage", explain:"Storage medium for data. ", phonetic:"[kəmˈpækt dɪsk ˈstɔː.rɪdʒ]"},
    {word:"Compatibility testing", explain:"Ensuring software works on different systems. ", phonetic:"[kəmˌpæt.əˈbɪl.ə.ti ˈtes.tɪŋ]"},
    {word:"Compiler", explain:"Translates programming code into machine-readable instructions.  ", phonetic:"[kəmˈpaɪ.lər]"},
    {word:"Compliance audits", explain:"Evaluations to ensure that software processes and practices adhere to established standards and regulations.  ", phonetic:"[kəmˈplaɪ.əns ˈɔː.dɪt]"},
    {word:"Compliance", explain:"Adhering to laws, regulations, and industry standards relevant to software development and operation.  ", phonetic:"[kəmˈplaɪ.əns]"},
    {word:"Component test", explain:"Tests individual parts of a larger software system.  ", phonetic:"[kəmˈpəʊ.nənt ˈtest]"},
    {word:"Compress", explain:"Reduce the size of a file to save space or to transmit it at a faster speed.", phonetic:"[kəmˈpres]"},
    {word:"Condition", explain:"Statement defining if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən]"},
    {word:"Conditional code", explain:"Code that executes based on specific conditions.", phonetic:"[kənˈdɪʃ.ən.əl kəʊd]"},
    {word:"Conditional statement", explain:"A statement that defines if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən.əl ˈsteɪt.mənt]"},
    {word:"Connector", explain:"Links different parts of a system or program.", phonetic:"[kəˈnek.tər]"},
    {word:"Console", explain:"Text-based interface for interacting with a computer.", phonetic:"[kənˈsəʊl]"},
    {word:"Containers", explain:"Packaging of software with all its dependencies for easy deployment.", phonetic:"[kənˈteɪ.nərs]"},
    {word:"Continuous delivery", explain:"Automating the process of delivering software changes to a staging or production environment.", phonetic:"[kənˈtɪn.ju.əs dɪˈlɪv.ər.i]"},
    {word:"Continuous deployment", explain:"Automating the release and deployment of software changes to production.", phonetic:"[kənˈtɪn.ju.əs dɪˈplɔɪ.mənt]"},
    {word:"Continuous integration", explain:"The practice of regularly integrating code changes into a shared repository, ensuring early detection of integration issues in the development process.", phonetic:"[kənˈtɪn.ju.əs ˌɪn.tɪˈɡreɪ.ʃən]"},
    {word:"Cookies", explain:"Small files stored on a user's device by websites.", phonetic:"[ˈkʊk.is]"},
    {word:"CPU", explain:"Central processing unit, main brain of a computer.", phonetic:"[ˌsiː.piːˈjuː]"},
    {word:"Cross-browser compatibility", explain:"Ensuring that web applications function consistently across different web browsers.", phonetic:"[krɒs ˈbraʊ.zər kəmˌpæt.əˈbɪl.ə.ti]"},
    {word:"Cross-platform development", explain:"Creating software that can run on multiple operating systems or platforms.", phonetic:"[krɒs ˈplæt.fɔːm dɪˈvel.əp.mənt]"},
    {word:"CRUD", explain:"Create, Read, Update, Delete basic operations on data.", phonetic:"[krʌd]"},
    {word:"Cryptography", explain:"The study and application of techniques for secure communication and data protection.", phonetic:"[krɪpˈtɒɡ.rə.fi]"},
    {word:"Cyber Threat Intelligence", explain:"Information about potential cyber threats to inform decision-making and response.", phonetic:"[ˈsaɪ.bər θret ɪnˈtel.ɪ.dʒəns]"},
    {word:"Cybersecurity Frameworks", explain:"Comprehensive structures outlining best practices for managing cybersecurity risks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈfreɪm.wɜːks]"},
    {word:"Cybersecurity measures", explain:"Actions taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈmeʒ.ərs]"},
    {word:"Cybersecurity", explain:"Measures taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti]"},

    {word:"Daemon", explain:"UNIX application that is permanently on alert on a server in order to perform certain tasks.", phonetic:"[ˈdiː.mən]"},
    {word:"Data analysis", explain:"Examining and interpreting data to extract meaningful insights.", phonetic:"[ˈdeɪ.tə əˈnæl.ə.sɪs]"},
    {word:"Data backup", explain:"Copying and storing data for recovery in case of loss.", phonetic:"[ˈdeɪ.tə ˈbæk.ʌp]"},
    {word:"Database", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs]"},
    {word:"Data center", explain:"Place to place large quantities of servers and communication equipment; It has all the facilities of bandwidth, physical security, 24-hour air conditioning, etc.", phonetic:"[ˈdeɪ.tə ˈsen.tər]"},
    {word:"Data integrity", explain:"Ensuring the accuracy and consistency of data throughout its lifecycle.", phonetic:"[ˈdeɪ.tə ɪnˈteɡ.rə.ti]"},
    {word:"Data privacy", explain:"Protecting the confidentiality and integrity of personal or sensitive information.", phonetic:"[ˈdeɪ.tə ˈprɪv.ə.si]"},
    {word:"Data shape", explain:"Structure of data, including its organization and types.", phonetic:"[ˈdeɪ.tə ʃeɪp]"},
    {word:"Data structure", explain:"The organization and types of data.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃər]"},
    {word:"Data structures", explain:"Organized formats for storing and managing data, such as arrays, lists, and trees.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃərs]"},
    {word:"Database administrator (DBA)", explain:"Manages and maintains databases.", phonetic:"[ˈdeɪ.tə.beɪs ədˈmɪn.ɪ.streɪ.tər]"},
    {word:"Database management", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs ˈmæn.ɪdʒ.mənt]"},
    {word:"DDL (data definition language)", explain:"A subset of SQL that defines and manages database structures.", phonetic:"[ˈdeɪ.tə ˌdef.ɪˈnɪʃ.ən ˈlæŋ.ɡwɪdʒ]"},
    {word:"DDoS", explain:"Distributed Denial of Service. It is an attack with a multitude of systems that have been 'hacked' directed at a particular target.", phonetic:"[ˈdiː.dɒs]"},
    {word:"Debugging breakpoint", explain:"Pausing program execution to identify and fix errors.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈbreɪkpɔɪnt]"},
    {word:"Debugging process", explain:"Finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈprəʊ.ses]"},
    {word:"Debugging tools", explain:"Software tools used by developers to identify and fix errors or issues in their code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ tuːls]"},
    {word:"Debugging", explain:"Process of finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ]"},
    {word:"Decision", explain:"Choice made between different options.", phonetic:"[dɪˈsɪʒ.ən]"},
    {word:"Decision-making", explain:"The process of choosing between different options.", phonetic:"[dɪˈsɪʒ.ən ˈmeɪ.kɪŋ]"},
    {word:"Declaration", explain:"Specifies a variable, function, or other entity in code.", phonetic:"[ˌdek.ləˈreɪ.ʃən]"},
    {word:"Dependency Management", explain:"Handling and organizing the external libraries and components that a software project relies on.", phonetic:"[dɪˈpen.dən.si ˈmæn.ɪdʒ.mənt]"},
    {word:"Deployment", explain:"The process of releasing and installing a software application for use in a specific environment.", phonetic:"[dɪˈplɔɪ.mənt]"},
    {word:"Design patterns", explain:"Reusable solutions to common problems in software design, providing templates for solving issues in a flexible and efficient way.", phonetic:"[dɪˈzaɪn ˈpæt.əns]"},
    {word:"Designate", explain:"Assign or label something with a specific name or purpose.", phonetic:"[ˈdez.ɪɡ.neɪt]"},
    {word:"Development environment", explain:"The set of tools, processes, and configurations used by developers to write, test, and debug software.", phonetic:"[dɪˈvel.əp.mənt ɪnˈvaɪ.rə.mənt]"},
    {word:"Device", explain:"Electronic equipment with specific functions.", phonetic:"[dɪˈvaɪs]"},
    {word:"DevOps", explain:"Culture and practice of collaboration between development and operations teams.", phonetic:"[dɪv ɒps]"},
    {word:"DevSecOps", explain:"Integrating security practices into the DevOps (Development and Operations) process.", phonetic:"[dɪv sek ɒps]"},
    {word:"Disaster recovery planning", explain:"Developing strategies to recover IT systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i ˈplæn.ɪŋ]"},
    {word:"Disaster recovery", explain:"Planning and procedures for restoring and recovering systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i]"},
    {word:"Display", explain:"Screen or other device for showing visual information.", phonetic:"[dɪˈspleɪ]"},
    {word:"DJango", explain:"High-level web framework written in Python.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"DML (data manipulation language)", explain:"A subset of SQL that manipulates and queries data within a database.", phonetic:"[ˈdeɪ.tə məˌnɪp.jəˈleɪ.ʃən ˈlæŋ.ɡwɪdʒ]"},
    {word:"Document", explain:"A file containing information, usually in electronic format.", phonetic:"[ˈdɒk.jə.mənt]"},
    {word:"Documentation", explain:"A set of documents that describe a system, software, or process.", phonetic:"[ˌdɒk.jə.menˈteɪ.ʃən]"},
    {word:"DOM", explain:"Document Object Model, a tree-like representation of the content of a web page.", phonetic:"[dɒm]"},
    {word:"Domain", explain:"A unique name that identifies a website on the internet.", phonetic:"[dəˈmeɪnʒ]"},
    {word:"Drag", explain:"To move an object on a touchscreen or with a mouse.", phonetic:"[dræɡ]"},

    {word:"Encryption", explain:"The process of converting information into a secure code to protect it from unauthorized access.", phonetic:"[ɪnˈkrip.ʃən]"},
    {word:"Error Handling", explain:"Managing and addressing errors that occur during the execution of a program.", phonetic:"[ˈer.ər ˈhænd.lɪŋ]"},
    {word:"Event", explain:"An action that occurs in a system or program.", phonetic:"[ɪˈvent]"},
    {word:"Exception Handling", explain:"The process of managing and responding to unexpected events or errors in software.", phonetic:"[ɪkˈsep.ʃən ˈhænd.lɪŋ]"},
    {word:"Extract", explain:"To obtain data from one source and store it in another location.", phonetic:"[ɪkˈstrækt]"},

    {word:"Firewall configuration", explain:"Setting up security measures to control incoming and outgoing network traffic.", phonetic:"[ˈfaɪə.wɔːl kənˌfɪɡ.əˈreɪ.ʃən]"},
    {word:"Flesh out", explain:"To expand or complete details of a plan or idea.", phonetic:"[fleʃ aʊt]"},
    {word:"Floppy disk", explain:"An outdated portable magnetic storage device.", phonetic:"[ˈflɒp.i dɪsk]"},
    {word:"Flowchart", explain:"A graphical representation of the steps in a process.", phonetic:"[ˈfləʊ.tʃɑːt]"},
    {word:"Fluid design", explain:"A web design that automatically adapts to different screen sizes.", phonetic:"[ˈfluː.ɪd dɪˈzaɪn]"},
    {word:"Framework", explain:"A set of tools and libraries for developing software.", phonetic:"[ˈfreɪm.wɜːk]"},
    {word:"Frameworks", explain:"Pre-built structures and tools that provide a foundation for developing software applications.", phonetic:"[ˈfreɪm.wɜːks]"},
    {word:"Frontend development", explain:"Creating the user interface and user experience components of a software application.", phonetic:"[ˌfrʌnt.end dɪˈvel.əp.mənt]"},
    {word:"Frontend", explain:"The part of a website or application that is visible and interactive for the user.", phonetic:"[ˌfrʌnt.end]"},
    {word:"Full-stack", explain:"Software development that encompasses both the frontend and backend.", phonetic:"[fʊl-stæk]"},
    {word:"Function", explain:"A block of code that performs a specific task.", phonetic:"[ˈfʌŋk.ʃən]"},
    {word:"Functional programming", explain:"A programming paradigm where computation is treated as the evaluation of mathematical functions, avoiding changing state and mutable data.", phonetic:"[ˈfʌŋk.ʃən.əl ˈprəʊ.ɡræm.ɪŋ]"},

    {word:"Git", explain:"A distributed version control system for tracking changes in code.", phonetic:"[ɡɪt]"},
    {word:"Github", explain:"A hosting platform for Git projects.", phonetic:"[ɡɪt hʌb]"},
    {word:"Gitlab", explain:"Similar to Github, a platform for hosting Git projects.", phonetic:"[ɡɪt læb]"},
    {word:"Go", explain:"A modern programming language developed by Google.", phonetic:"[ɡəʊ]"},

    {word:"Hacker", explain:"A person with computer skills who uses them for unauthorized purposes.", phonetic:"[ˈhæk.ər]"},
    {word:"Hacking", explain:"The attempt to gain unauthorized access to a computer system or network.", phonetic:"[ˈhæk.ɪŋ]"},
    {word:"Hard drive", explain:"A magnetic storage device that stores data on a spinning disk.", phonetic:"[hɑːd draɪv]"},
    {word:"Hardware", explain:"The physical components of a computer system.", phonetic:"[ˈhɑːd.weər]"},
    {word:"HDMI", explain:"High-Definition Multimedia Interface. It is a digital interface to transmit audio and video data on the same cable. Most HDTVs, DVDs, Blu-rays, cable boxes, and game consoles have HDMI support.", phonetic:"[ˌeɪtʃ.diː.emˈaɪ]"},
    {word:"Headphones", explain:"An audio device that is worn over the ears.", phonetic:"[ˈhed.fəʊnz]"},
    {word:"Highlight", explain:"To emphasize or make something more visible.", phonetic:"[ˈhaɪ.laɪt]"},
    {word:"Hosting", explain:"A service that provides space on a server to store web files.", phonetic:"[ˈhəʊstɪŋ]"},
    {word:"HTML", explain:"HyperText Markup Language defines the structure and content of web pages.", phonetic:"[ˌeɪtʃ.tiː.emˈel]"},
    {word:"HTTP", explain:"HyperText Transfer Protocol, the protocol for transferring data on the web.", phonetic:"[ˌeɪtʃ.tiː.tiːˈpiː]"},
    {word:"Hyperlink", explain:"A link in an electronic document that takes you to another location.", phonetic:"[ˈhaɪ.pə.lɪŋk]"},

    {word:"Iaas", explain:"Infrastructure as a Service, a cloud computing model that provides infrastructure as a service.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"IDE", explain:"Integrated Development Environment, an environment for creating software.", phonetic:"[aɪˈdi]"},
    {word:"Incident management", explain:"The process of identifying, responding to, and resolving incidents or issues in a system.", phonetic:"[ˈɪn.sɪ.dənt ˈmæn.ɪdʒ.mənt]"},
    {word:"Incident response", explain:"Coordinated actions taken in response to a security incident or breach.", phonetic:"[ˈɪn.sɪ.dənt rɪˈspɒns]"},
    {word:"Infrastructure", explain:"The physical and virtual components that form the basis of a computer system.", phonetic:"[ˈɪn.frəˌstrʌk.tʃər]"},
    {word:"Input device", explain:"A device used to enter data into a computer system.", phonetic:"[ˈɪn.pʊt dɪˈvaɪs]"},
    {word:"Integration test", explain:"A test that verifies how different components of a system interact.", phonetic:"[ˌɪn.tɪˈɡreɪ.ʃən test]"},
    {word:"Internal storage", explain:"The storage space on an electronic device.", phonetic:"[ɪnˈtɜː.nəl ˈstɔː.rɪdʒ]"},
    {word:"Intrusion detection", explain:"Detecting and responding to unauthorized access or security breaches.", phonetic:"[ɪnˈtruː.ʒən dɪˈtek.ʃən]"},
    {word:"Involve", explain:"To include or make someone participate in something.", phonetic:"[ɪnˈvɒlv]"},
    
    {word:"Java", explain:"A general-purpose object-oriented programming language.", phonetic:"[ˈdʒɑː.və]"},
    {word:"JavaScript", explain:"A programming language that allows user interaction on web pages.", phonetic:"[ˈdʒɑː.və skrɪpt]"},
    {word:"JSON", explain:"A lightweight data-interchange format used for easy data exchange between applications.", phonetic:"[ˈd͡ʒeɪsən]"},

    {word:"Keyboard", explain:"An input device that allows you to type letters, numbers, and symbols.", phonetic:"[ˈkiː.bɔːd]"},

    {word:"Library", explain:"A collection of reusable code for performing specific tasks.", phonetic:"[ˈlaɪ.brər.i]"},
    {word:"Load balancing", explain:"Distributing network traffic evenly across multiple servers to ensure optimal performance.", phonetic:"[ləʊd ˈbæl.ən.sɪŋ]"},
    {word:"Load test", explain:"Tests that verify the performance of a system under load.", phonetic:"[ləʊd ˈtest]"},
    {word:"Log", explain:"A file that records events and activities in a system.", phonetic:"[lɒɡ]"},
    {word:"Logging", explain:"Recording events, activities, or errors in a system for analysis and troubleshooting.", phonetic:"[ˈlɒɡ.ɪŋ]"},
    {word:"Loops", explain:"Sections of code that execute repeatedly until a condition is met.", phonetic:"[luːps]"},
    
    {word:"Manual input", explain:"The process of entering data into a computer system manually.", phonetic:"[ˈmæn.ju.əl ˈɪn.pʊt]"},
    {word:"Manual operation", explain:"The process of performing a task in a computer system manually.", phonetic:"[ˈmæn.ju.əl ˌɒp.ərˈeɪ.ʃən]"},
    {word:"Merge", explain:"To integrate two or more things into one.", phonetic:"[mɜːdʒ]"},
    {word:"Microphone", explain:"A device that converts sound into an electrical signal.", phonetic:"[ˈmaɪ.krə.fəʊn]"},
    {word:"Microservices", explain:"An architectural style where an application is composed of small, independent services.", phonetic:"[ˈmaɪ.krə.sɜː.vɪs]"},
    {word:"Middleware", explain:"Software that acts as an intermediary between different software components.", phonetic:"[ˈmɪd.əl.weər]"},
    {word:"Mixin", explain:"A reusable piece of code that can be included in other classes.", phonetic:"[mɪksɪŋ]"},
    {word:"Mobile applications", explain:"Software designed to operate on mobile devices such as smartphones and tablets.", phonetic:"[ˈməʊ.baɪl ˌæp.lɪˈkeɪ.ʃəns]"},
    {word:"Mobile development", explain:"Creating apps for smartphones, tablets, and wearables.", phonetic:"[ˈməʊ.baɪl dɪˈvel.əp.mənt]"},
    {word:"Mobile OS", explain:"Operating system designed for mobile devices, e.g., Android.", phonetic:"[ˈməʊ.baɪl ɒs]"},
    {word:"Modem", explain:"Modulates/demodulates signals for communication.", phonetic:"[ˈməʊ.dem]"},
    {word:"Monitor", explain:"Display to visualize computer output.", phonetic:"[ˈmɒn.ɪ.tər]"},
    {word:"Monitoring", explain:"Continuously observing and measuring the performance and behavior of a system.", phonetic:"[ˈmɒn.ɪ.tə.rɪŋ]"},
    {word:"Monolith", explain:"Large application with all functionalities.", phonetic:"[ˈmɒn.ə.lɪθ]"},
    {word:"Mouse", explain:"Device to control the cursor on the screen.", phonetic:"[maʊs]"},
    {word:"MVP", explain:"Minimum viable product to validate an idea.", phonetic:"[ˌem.viːˈpiː]"},

    {word:"Network bandwidth", explain:"The amount of data that can be transmitted in a given time.", phonetic:"[ˈnet.wɜːk ˈbænd.wɪtθ]"},
    {word:"Network security", explain:"Protecting a computer network infrastructure against unauthorized access and attacks.", phonetic:"[ˈnet.wɜːk sɪˈkjʊə.rə.ti]"},
    {word:"NoSQL database", explain:"Stores data in a flexible format.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},

    {word:"Objective-C", explain:"Programming language for iOS and macOS.", phonetic:"[əbˈdʒek.tɪv siː]"},
    {word:"Object-Oriented programming (OOP)", explain:"A programming paradigm that uses objects, which encapsulate data and behavior, for software development.", phonetic:"[ˈɒb.dʒɪkt ˈɔː.ri.en.tɪd ˈprəʊ.ɡræm.ɪŋ]"},
    {word:"OEM", explain:"Original Equipment Manufacturer, it refers to companies that manufacture and package products for others, and also to companies that acquire a product or component and reuse it or incorporate it into another new product with their own brand.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"Open source", explain:"Accessible and modifiable source code.", phonetic:"[ˈəʊ.pən sɔːs]"},
    {word:"Operators", explain:"Companies that provide telecommunications services.", phonetic:"[ˈɒp.ər.eɪ.tərs]"},
    {word:"Organization chart", explain:"A diagram that shows the hierarchical structure of an organization.", phonetic:"[ˌɔː.ɡən.aɪˈzeɪ.ʃən tʃɑːt]"},
    {word:"Outcome", explain:"Consequence of an action or process.", phonetic:"[ˈaʊt.kʌm]"},
    {word:"Output", explain:"Information or data produced by a system.", phonetic:"[ˈaʊt.pʊt]"},
    
    {word:"PaaS", explain:"Platform to develop, deploy, and manage applications.", phonetic:"[pɑːs]"},
    {word:"Penetration Testing", explain:"Simulating cyber-attacks to identify vulnerabilities and weaknesses in a system.", phonetic:"[ ˌpenɪˈtreɪʃən ˈtes.tɪŋ]"},
    {word:"Performance benchmark", explain:"Comparing the performance of different systems or software.", phonetic:"[pəˈfɔː.məns ˈbentʃ.mɑːk]"},
    {word:"Performance Monitoring", explain:"Tracking and analyzing the performance of a system during its operation.", phonetic:"[pəˈfɔː.məns ˈmɒn.ɪ.tər]"},
    {word:"Performance Optimization", explain:"Improving the efficiency and speed of a software application.", phonetic:"[pəˈfɔː.məns ˌɒp.tɪ.maɪˈzeɪ.ʃən]"},
    {word:"Performance Test", explain:"Performance measurement under real load.", phonetic:"[pəˈfɔː.məns test]"},
    {word:"Perl", explain:"Versatile language for web development and system administration.", phonetic:"[pɜːl]"},
    {word:"PHP", explain:"Language for developing dynamic web applications.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    {word:"Plugin", explain:"Module that adds functionalities to a program.", phonetic:"[ˈplʌɡ.ɪn]"},
    {word:"Plugs", explain:"Connectors to connect devices.", phonetic:"[plʌɡs]"},
    {word:"Port", explain:"Logical connection for communication between devices.", phonetic:"[pɔːt]"},
    {word:"Predefined process", explain:"A set of steps established beforehand to guide a particular action or task.", phonetic:"[ˌpriː.dɪˈfaɪnd ˈprəʊ.ses]"},
    {word:"Preparation", explain:"The act of getting ready for something, often involving gathering necessary materials and information.", phonetic:"[ˌprep.ərˈeɪ.ʃən]]"},
    {word:"Printed document", explain:"A physical copy of a document with text and/or images, created using a printer.", phonetic:"[ˈprɪn.tɪd ˈdɒk.jə.mənt]"},
    {word:"Printer", explain:"A device that produces printed documents from digital files.", phonetic:"[ˈprɪn.tər]"},
    {word:"Privilege management", explain:"Controlling and assigning specific privileges or permissions to users.", phonetic:"[ˈprɪv.əl.ɪdʒ]"},
];