const glosary=[
    { num:1, word:"Acceptance criteria", explain:"Conditions that a system must meet to be accepted by a user or stakeholders.", phonetic:"[əkˈseptənts kraɪˈtɪərɪə]", image:"1.jpg"},
    { num:2, word:"Acceptance tests", explain:"Confirm that system meets user requirements before final deployment.", phonetic:"[əkˈseptənts ˈtest]", image:"2.jpeg"},
    { num:3, word:"Access Control", explain:"Managing and regulating access to resources or systems.", phonetic:"[ˈækses kənˈtrəʊl]", image:"3.jpeg"},
    { num:4, word:"Acts", explain:"Individual commands in a script or program.", phonetic:"[ˈækts]", image:"4.png"},
    { num:5, word:"Adaptive design", explain:"Adjusts website layout to different screen sizes.", phonetic:"[əˈdæp.tɪv dɪˈzaɪn]", image:"5.png"},
    { num:6, word:"Adjustment", explain:"A minor change made to a system or process / Small change to system or process.", phonetic:"[əˈdʒʌst.mənt]", image:"6.jpeg"},
    { num:7, word:"Agile methodology", explain:"An iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˌmeθ.əˈdɒl.ə.dʒi]", image:"7.jpeg"},
    { num:8, word:"Agile software development", explain:"Iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˈsɒft.weər dɪˈvel.əp.mənt]", image:"8.jpeg"},
    { num:9, word:"AI", explain:"Artificial Intelligence, a branch of computer science that seeks to create intelligent systems.", phonetic:"[ˌeɪˈaɪ]", image:"9.jpeg"},
    { num:10, word:"AJAX", explain:"Technique for asynchronous web page updates.", phonetic:"[ˈeɪʤæks]", image:"10.png"},
    { num:11, word:"Algorithm", explain:"Set of instructions for solving a problem.", phonetic:"[ˈæl.ɡə.rɪ.ðəm]", image:"11.png"},
    { num:12, word:"Algorithmic solution", explain:"A set of step-by-step instructions to solve a specific problem.", phonetic:"[ˌæl.ɡəˈrɪð.mɪk səˈluː.ʃən]", image:"12.png"},
    { num:13, word:"Analysis", explain:"The process of examining and breaking down a complex system or problem into smaller parts to understand its components and relationships.", phonetic:"[əˈnæl.ə.sɪs]", image:"13.jpeg"},
    { num:14, word:"Android", explain:"Mobile operating system developed by Google.", phonetic:"[ˈæn.drɔɪd]", image:"14.png"},
    { num:15, word:"API integration", explain:"Connecting different software components to enable communication.", phonetic:"[ˌeɪ.piˈaɪ ˌɪn.tɪˈɡreɪ.ʃən]", image:"15.png"},
    { num:16, word:"API", explain:"Interface for software components to interact. ", phonetic:"[ˌeɪ.piˈaɪ]", image:"16.png"},
    { num:17, word:"Architecture", explain:"The high-level structure or design of a system, defining its components and their interactions to achieve specific objectives", phonetic:"[ˈɑː.kɪ.tek.tʃər]", image:"17.png"},
    { num:18, word:"ASCII", explain:"Code that numerically represents a character, such as 'a' or '@.'.", phonetic:"[ˈæs.ki]", image:"18.jpeg"},
    { num:19, word:"Asynchronouns", explain:"A technique where tasks operate independently and don't wait for each other to complete.", phonetic:"[eɪˈsɪŋkrənəs]", image:"19.png"},
    { num:20, word:"Authentication", explain:"Verifying the identity of a user or system to ensure secure access.", phonetic:"[ɔːˌθen.tɪˈkeɪ.ʃən]", image:"20.png"},
    { num:21, word:"Authorization", explain:"Granting appropriate access rights to users or systems based on their authenticated identity.", phonetic:"[ˌɔː.θər.aɪˈzeɪ.ʃən]", image:"21.png"},
    { num:22, word:"Automated test", explain:"Test run automatically by software.", phonetic:"[ˈɔː.tə.meɪ.tɪd ˈtest]", image:"22.png"},

    { num:23, word:"Backdoor", explain:"Unauthorized access point to a system. ", phonetic:"[ˈbæk.dɔːr]", image:"23.png"},
    { num:24, word:"Backend Development", explain:"Writing server-side logic and handling database interactions to support the functionality of a software application.", phonetic:"[ˌbæk.end dɪˈvel.əp.mənt]", image:"24.png"},
    { num:25, word:"Backup", explain:"Copy of data used for recovery in case of loss.", phonetic:"[ˌˈbæk.ʌp]", image:"25.jpeg"},
    { num:26, word:"Bandwidth", explain:"Amount of data transferrable in a given time. ", phonetic:"[ˈbænd.wɪtθ]", image:"26.jpeg"},
    { num:27, word:"Batch", explain:"It is a file that chains commands that are carried out by the PC when it is invoked.", phonetic:"[bætʃ]", image:"27.png"},
    { num:28, word:"BCC", explain:"BCC is the acronym for 'Blind Carbon Copy'.", phonetic:"[ˌbiːsiːˈsiː]", image:"28.jpeg"},
    { num:29, word:"Benchmarking", explain:"Comparing performance of different systems or software. ", phonetic:"[ˈbentʃˌmɑː.kɪŋ]", image:"29.jpeg"},
    { num:30, word:"Big data analytics", explain:"Analyzing large and complex datasets for insights.", phonetic:"[bɪɡ ˈdeɪ.tə ˌæn.əlˈɪt.ɪks]", image:"30.png"},
    { num:31, word:"Big data", explain:"Large and complex datasets requiring specialized processing. ", phonetic:"[bɪɡ ˈdeɪ.tə]", image:"31.jpg"},
    { num:32, word:"Binary code", explain:"Machine-readable code using 0s and 1s. ", phonetic:"[ˈbaɪ.nər.i kəʊd]", image:"32.jpeg"},
    { num:33, word:"Binary digit (Bit)", explain:"The smallest unit of data storage, either 0 or 1.", phonetic:"[ˈbaɪ.nər.i ˈdɪdʒ.ɪt]", image:"32.jpeg"},
    { num:34, word:"Binary large object (BLOB)", explain:"Storing data without a specific format.", phonetic:"[ˈbaɪ.nər.i lɑːdʒ ˈɒb.dʒɪkt]", image:"34.jpg"},
    { num:35, word:"Binary representation", explain:"Binary representation is a way of representing data using only two states or values: 0s and 1s. It is used by computers and other digital systems to encapsulate and manipulate numerical values.", phonetic:"[ˈbaɪ.nər.i ˌrep.rɪ.zenˈteɪ.ʃən]", image:"35.png"},
    { num:36, word:"BIOS initialization", explain:"Basic Input/Output System starting hardware during computer startup.", phonetic:"[ˈbaɪ.ɒs ɪˈnɪʃ.əl.aɪz]", image:"36.jpeg"},
    { num:37, word:"BIOS", explain:"Basic input/output system, initializes hardware during startup.", phonetic:"[ˈbaɪ.ɒs]", image:"37.jpeg"},
    { num:38, word:"Bitbucket", explain:"Software development platform similar to GitHub.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"38.jpeg"},
    { num:39, word:"BLOB", explain:"Binary large object, data stored without specific format.", phonetic:"[blɒb]", image:"39.png"},
    { num:40, word:"Blockchain technology", explain:"A secure digital ledger using cryptographic techniques.", phonetic:"[ˈblɒk.tʃeɪn tekˈnɒl.ə.dʒi]", image:"40.jpeg"},
    { num:41, word:"Blockchain", explain:"Digital ledger of transactions secured through cryptography.", phonetic:"[ˈblɒk.tʃeɪn]", image:"41.jpeg"},
    { num:42, word:"Boot", explain:"Starting up a computer or device.", phonetic:"[buːt]", image:"42.jpg"},
    { num:43, word:"Bootstrap", explain:"Front-end framework for web development. ", phonetic:"[ˈbuːt.stræp]", image:"43.jpg"},
    { num:44, word:"Bootstrapping", explain:"Self-starting a computer or device. ", phonetic:"[ˈbuːtˌstræpɪŋ]", image:"44.jog"},
    { num:45, word:"Botnet network", explain:"A network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net ˈnet.wɜːk]", image:"45.png"},
    { num:46, word:"Botnet", explain:"Network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net]", image:"46.png"},
    { num:47, word:"Branch", explain:"Different versions of code within a single project.", phonetic:"[brɑːntʃ]", image:"47.png"},
    { num:48, word:"Breakpoint", explain:"Pause execution of program to debug.", phonetic:"[ˈbreɪkpɔɪnt]", image:"48.png"},
    { num:49, word:"Browser", explain:"Software used to access websites.", phonetic:"[ˈbraʊ.zər]", image:"49.jpeg"},
    { num:50, word:"Bug", explain:"Error in software code causing issues.", phonetic:"[bʌɡ]", image:"50.jpeg"},
    { num:51, word:"Business analysis", explain:"Analyzing business needs and translating them into technical requirements.", phonetic:"[ˈbɪz.nɪs əˈnæl.ə.sɪs]", image:"51.jpeg"},
    { num:52, word:"Business continuity", explain:"Planning and processes to ensure that critical business functions can continue in the face of disruptions.", phonetic:"[ˈbɪz.nɪs ˌkɒn.tɪˈnjuː.ə.ti]", image:"52.jpeg"},
    { num:53, word:"Byte storage", explain:"The basic unit of information in computer storage and processing. A byte consists of 8 adjacent binary digits (bits), each of which consists of a 0 or 1.", phonetic:"[baɪt ˈstɔː.rɪdʒ]", image:"53.png"},
    { num:54, word:"Byte", explain:"Group of 8 bits, basic unit of memory and storage.", phonetic:"[baɪt]", image:"54.png"},
    
    { num:55, word:"C#", explain:"Object-oriented programming language developed by Microsoft.", phonetic:"[siː] /chart/", image:"55.png"},
    { num:56, word:"C", explain:"General-purpose programming language.", phonetic:"[siː]", image:"56.png"},
    { num:57, word:"C++", explain:"General-purpose programming language based on C.", phonetic:"[siː] /plus plus/", image:"57.jpeg"},
    { num:58, word:"Cache", explain:"Copy that a computer maintains of the recently visited web pages, if the user requests them, they are read from the hard drive without having to connect to the network again; thus, achieving a very noticeable improvement in speed.", phonetic:"[kæʃ]", image:"58.png"},
    { num:59, word:"Captcha", explain:"Completely Automated Public Turing, or Completely Automated Public Turing. It is a small test that helps determine whether a user is a computer or a human.", phonetic:"[ˈkæp.tʃə]", image:"59.jpeg"},
    { num:60, word:"Carriers", explain:"Telecommunications operators who own the Internet backbone networks and are responsible for data transport.", phonetic:"[ˈkær.i.ərs]", image:"60.png"},
    { num:61, word:"Cascading Style Sheets (CSS)", explain:"Defines the visual style of web pages.", phonetic:"[ˌsiː.esˈes] or [kæsˌkeɪ.dɪŋ ˈstaɪl ˌʃiːt]", image:"61.png"},
    { num:62, word:"CD", explain:"Compact disc for storing data.", phonetic:"[ˌsiːˈdiː]", image:"62.png"},
    { num:63, word:"CD-RW", explain:"Rewritable compact disc, which can be written, erased and rewritten over.", phonetic:"[ˌsiː.diː.ɑːˈdʌb.əl.juː]", image:"63.jpg"},
    { num:64, word:"Central processing unit (CPU)", explain:"The main brain of a computer.", phonetic:"[ˈsen.trəl ˈprəʊ.ses.ɪŋ ˈjuː.nɪt]", image:"64.jpeg"},
    { num:65, word:"Client-Side Scripting", explain:"Executing scripts on the user's browser to enhance interactivity.", phonetic:"[ˈklaɪ.ənt-saɪd skrɪp.tɪŋ]", image:"65.png"},
    { num:66, word:"Cloud computing", explain:"Accessing services over the internet instead of locally.", phonetic:"[klaʊd kəmˈpjuː.tɪŋ]", image:"66.jpeg"},
    { num:67, word:"Cloud service", explain:"Services accessed over the internet instead of being hosted locally.", phonetic:"[klaʊd ˈsɜː.vɪs]", image:"67.png"},
    { num:68, word:"Cluster", explain:"Hard drive storage unit. ", phonetic:"[ˈklʌs.tər]", image:"68.jpeg"},
    { num:69, word:"Code branching", explain:"Creating different versions of code within a single project.", phonetic:"[kəʊd brɑːnt.ʃɪŋ]", image:"69.jpeg"},
    { num:70, word:"Code compilation", explain:"Translating programming code into machine-readable instructions.", phonetic:"[kəʊd ˌkɒm.pɪˈleɪ.ʃən]", image:"70.jpeg"},
    { num:71, word:"Code declaration", explain:"Specifying a variable, function, or other entity in code.", phonetic:"[kəʊd ˌdek.ləˈreɪ.ʃən]", image:"71.jpeg"},
    { num:72, word:"Code refactoring", explain:"Restructuring existing code to improve its readability, maintainability, and efficiency.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"72.jpeg"},
    { num:73, word:"Code review", explain:"The systematic examination of source code to find and fix issues, ensure quality, and share knowledge among team members.", phonetic:"[kəʊd rɪˈvjuː]", image:"73.png"},
    { num:74, word:"Code smells", explain:"Indicators of potential issues in code, suggesting the need for refactoring.", phonetic:"[kəʊd smels]", image:"74.png"},
    { num:75, word:"Code ", explain:"Set of instructions for a computer to execute.", phonetic:"[kəʊd]", image:"75.jpeg"},
    { num:76, word:"Command execution ", explain:"Issuing instructions to a system or program.", phonetic:"[kəˈmɑːnd ˌek.sɪˈkjuː.ʃən]", image:"76.png"},
    { num:77, word:"Command", explain:"Instruction given to a system or program. ", phonetic:"[kəˈmɑːnd]", image:"77.png"},
    { num:78, word:"Commit", explain:"Submitting changes to a version control system like Git. ", phonetic:"[kəˈmɪt]", image:"78.png"},
    { num:79, word:"Compact disc storage", explain:"Storage medium for data. ", phonetic:"[kəmˈpækt dɪsk ˈstɔː.rɪdʒ]", image:"79.jpeg"},
    { num:80, word:"Compatibility testing", explain:"Ensuring software works on different systems. ", phonetic:"[kəmˌpæt.əˈbɪl.ə.ti ˈtes.tɪŋ]", image:"80.jpeg"},
    { num:81, word:"Compiler", explain:"Translates programming code into machine-readable instructions.  ", phonetic:"[kəmˈpaɪ.lər]", image:"81.jpg"},
    { num:82, word:"Compliance audits", explain:"Evaluations to ensure that software processes and practices adhere to established standards and regulations.  ", phonetic:"[kəmˈplaɪ.əns ˈɔː.dɪt]", image:"82.png"},
    { num:83, word:"Compliance", explain:"Adhering to laws, regulations, and industry standards relevant to software development and operation.  ", phonetic:"[kəmˈplaɪ.əns]", image:"83.jpeg"},
    { num:84, word:"Component test", explain:"Tests individual parts of a larger software system.  ", phonetic:"[kəmˈpəʊ.nənt ˈtest]", image:"84.png"},
    { num:85, word:"Compress", explain:"Reduce the size of a file to save space or to transmit it at a faster speed.", phonetic:"[kəmˈpres]", image:"85.jpeg"},
    { num:86, word:"Condition", explain:"Statement defining if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən]", image:"86.png"},
    { num:87, word:"Conditional code", explain:"Code that executes based on specific conditions.", phonetic:"[kənˈdɪʃ.ən.əl kəʊd]", image:"87.png"},
    { num:88, word:"Conditional statement", explain:"A statement that defines if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən.əl ˈsteɪt.mənt]", image:"88.jpeg"},
    { num:89, word:"Connector", explain:"Links different parts of a system or program.", phonetic:"[kəˈnek.tər]", image:"89.jpeg"},
    { num:90, word:"Console", explain:"Text-based interface for interacting with a computer.", phonetic:"[kənˈsəʊl]", image:"90.jpeg"},
    { num:91, word:"Containers", explain:"Packaging of software with all its dependencies for easy deployment.", phonetic:"[kənˈteɪ.nərs]", image:"91.png"},
    { num:92, word:"Continuous delivery", explain:"Automating the process of delivering software changes to a staging or production environment.", phonetic:"[kənˈtɪn.ju.əs dɪˈlɪv.ər.i]", image:"92.png"},
    { num:93, word:"Continuous deployment", explain:"Automating the release and deployment of software changes to production.", phonetic:"[kənˈtɪn.ju.əs dɪˈplɔɪ.mənt]", image:"93.jpeg"},
    { num:94, word:"Continuous integration", explain:"The practice of regularly integrating code changes into a shared repository, ensuring early detection of integration issues in the development process.", phonetic:"[kənˈtɪn.ju.əs ˌɪn.tɪˈɡreɪ.ʃən]", image:"94.png"},
    { num:95, word:"Cookies", explain:"Small files stored on a user's device by websites.", phonetic:"[ˈkʊk.is]", image:"95.jpeg"},
    { num:96, word:"CPU", explain:"Central processing unit, main brain of a computer.", phonetic:"[ˌsiː.piːˈjuː]", image:"96.png"},
    { num:97, word:"Cross-browser compatibility", explain:"Ensuring that web applications function consistently across different web browsers.", phonetic:"[krɒs ˈbraʊ.zər kəmˌpæt.əˈbɪl.ə.ti]", image:"97.jpeg"},
    { num:98, word:"Cross-platform development", explain:"Creating software that can run on multiple operating systems or platforms.", phonetic:"[krɒs ˈplæt.fɔːm dɪˈvel.əp.mənt]", image:"98.jpeg"},
    { num:99, word:"CRUD", explain:"Create, Read, Update, Delete basic operations on data.", phonetic:"[krʌd]", image:"99.jpeg"},
    { num:100, word:"Cryptography", explain:"The study and application of techniques for secure communication and data protection.", phonetic:"[krɪpˈtɒɡ.rə.fi]", image:"100.png"},
    { num:101, word:"Cyber Threat Intelligence", explain:"Information about potential cyber threats to inform decision-making and response.", phonetic:"[ˈsaɪ.bər θret ɪnˈtel.ɪ.dʒəns]", image:"101.png"},
    { num:102, word:"Cybersecurity Frameworks", explain:"Comprehensive structures outlining best practices for managing cybersecurity risks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈfreɪm.wɜːks]", image:"102.png"},
    { num:103, word:"Cybersecurity measures", explain:"Actions taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈmeʒ.ərs]", image:"103.jpeg"},
    { num:104, word:"Cybersecurity", explain:"Measures taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti]", image:"104.jpeg"},

    { num:105, word:"Daemon", explain:"UNIX application that is permanently on alert on a server in order to perform certain tasks.", phonetic:"[ˈdiː.mən]", image:"105.png"},
    { num:106, word:"DART", explain:"It is a programming language developed by Google, known for its use in mobile application development using the Flutter framework. It is also used for creating web and server applications.", phonetic:"[dɑːt]", image:"106.png"},
    { num:107, word:"Data analysis", explain:"Examining and interpreting data to extract meaningful insights.", phonetic:"[ˈdeɪ.tə əˈnæl.ə.sɪs]", image:"107.png"},
    { num:108, word:"Data backup", explain:"Copying and storing data for recovery in case of loss.", phonetic:"[ˈdeɪ.tə ˈbæk.ʌp]", image:"108.jpeg"},
    { num:109, word:"Database", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs]", image:"109.png"},
    { num:110, word:"Data center", explain:"Place to place large quantities of servers and communication equipment; It has all the facilities of bandwidth, physical security, 24-hour air conditioning, etc.", phonetic:"[ˈdeɪ.tə ˈsen.tər]", image:"110.png"},
    { num:111, word:"Data integrity", explain:"Ensuring the accuracy and consistency of data throughout its lifecycle.", phonetic:"[ˈdeɪ.tə ɪnˈteɡ.rə.ti]", image:"111.png"},
    { num:112, word:"Data privacy", explain:"Protecting the confidentiality and integrity of personal or sensitive information.", phonetic:"[ˈdeɪ.tə ˈprɪv.ə.si]", image:"112.jpeg"},
    { num:113, word:"Data shape", explain:"Structure of data, including its organization and types.", phonetic:"[ˈdeɪ.tə ʃeɪp]", image:"113.png"},
    { num:114, word:"Data structure", explain:"The organization and types of data.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃər]", image:"114.jpeg"},
    { num:115, word:"Data structures", explain:"Organized formats for storing and managing data, such as arrays, lists, and trees.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃərs]", image:"115.jpeg"},
    { num:116, word:"Database administrator (DBA)", explain:"Manages and maintains databases.", phonetic:"[ˈdeɪ.tə.beɪs ədˈmɪn.ɪ.streɪ.tər]", image:"116.jpeg"},
    { num:117, word:"Database management", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs ˈmæn.ɪdʒ.mənt]", image:"117.png"},
    { num:118, word:"DDL (data definition language)", explain:"A subset of SQL that defines and manages database structures.", phonetic:"[ˈdeɪ.tə ˌdef.ɪˈnɪʃ.ən ˈlæŋ.ɡwɪdʒ]", image:"118.jpeg"},
    { num:119, word:"DDoS", explain:"Distributed Denial of Service. It is an attack with a multitude of systems that have been 'hacked' directed at a particular target.", phonetic:"[ˈdiː.dɒs]", image:"119.jpeg"},
    { num:120, word:"Debugging breakpoint", explain:"Pausing program execution to identify and fix errors.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈbreɪkpɔɪnt]", image:"120.jpeg"},
    { num:121, word:"Debugging process", explain:"Finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈprəʊ.ses]", image:"121.png"},
    { num:122, word:"Debugging tools", explain:"Software tools used by developers to identify and fix errors or issues in their code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ tuːls]", image:"122.jpeg"},
    { num:123, word:"Debugging", explain:"Process of finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ]", image:"123.jpeg"},
    { num:124, word:"Decision", explain:"Choice made between different options.", phonetic:"[dɪˈsɪʒ.ən]", image:"124.jpeg"},
    { num:125, word:"Decision-making", explain:"The process of choosing between different options.", phonetic:"[dɪˈsɪʒ.ən ˈmeɪ.kɪŋ]", image:"125.png"},
    { num:126, word:"Declaration", explain:"Specifies a variable, function, or other entity in code.", phonetic:"[ˌdek.ləˈreɪ.ʃən]", image:"126.png"},
    { num:127, word:"Dependency Management", explain:"Handling and organizing the external libraries and components that a software project relies on.", phonetic:"[dɪˈpen.dən.si ˈmæn.ɪdʒ.mənt]", image:"127.png"},
    { num:128, word:"Deployment", explain:"The process of releasing and installing a software application for use in a specific environment.", phonetic:"[dɪˈplɔɪ.mənt]", image:"128.jpeg"},
    { num:129, word:"DER", explain:"Short for 'Entity-Relationship Diagram,'a tool used in database design to represent entities and the relationships between them.", phonetic:"[ˈdɛːˀr]", image:"129.jpeg"},
    { num:130, word:"Design patterns", explain:"Reusable solutions to common problems in software design, providing templates for solving issues in a flexible and efficient way.", phonetic:"[dɪˈzaɪn ˈpæt.əns]", image:"130.jpeg"},
    { num:131, word:"Designate", explain:"Assign or label something with a specific name or purpose.", phonetic:"[ˈdez.ɪɡ.neɪt]", image:"131.jpeg"},
    { num:132, word:"Development environment", explain:"The set of tools, processes, and configurations used by developers to write, test, and debug software.", phonetic:"[dɪˈvel.əp.mənt ɪnˈvaɪ.rə.mənt]", image:"132.jpeg"},
    { num:133, word:"Device", explain:"Electronic equipment with specific functions.", phonetic:"[dɪˈvaɪs]", image:"133.jpeg"},
    { num:134, word:"DevOps", explain:"Culture and practice of collaboration between development and operations teams.", phonetic:"[dɪv ɒps]", image:"134.png"},
    { num:135, word:"DevSecOps", explain:"Integrating security practices into the DevOps (Development and Operations) process.", phonetic:"[dɪv sek ɒps]", image:"135.jpeg"},
    { num:136, word:"Disaster recovery planning", explain:"Developing strategies to recover IT systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i ˈplæn.ɪŋ]", image:"136.jpeg"},
    { num:137, word:"Disaster recovery", explain:"Planning and procedures for restoring and recovering systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i]", image:"137.jpeg"},
    { num:138, word:"Display", explain:"Screen or other device for showing visual information.", phonetic:"[dɪˈspleɪ]", image:"138.jpeg"},
    { num:139, word:"DJango", explain:"High-level web framework written in Python.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"139.jpeg"},
    { num:140, word:"DML (data manipulation language)", explain:"A subset of SQL that manipulates and queries data within a database.", phonetic:"[ˈdeɪ.tə məˌnɪp.jəˈleɪ.ʃən ˈlæŋ.ɡwɪdʒ]", image:"140.jpeg"},
    { num:141, word:"Document", explain:"A file containing information, usually in electronic format.", phonetic:"[ˈdɒk.jə.mənt]", image:"141.png"},
    { num:142, word:"Documentation", explain:"A set of documents that describe a system, software, or process.", phonetic:"[ˌdɒk.jə.menˈteɪ.ʃən]", image:"142.jpeg"},
    { num:143, word:"DOM", explain:"Document Object Model, a tree-like representation of the content of a web page.", phonetic:"[dɒm]", image:"143.png"},
    { num:144, word:"Domain", explain:"A unique name that identifies a website on the internet.", phonetic:"[dəˈmeɪnʒ]", image:"144.png"},
    { num:145, word:"Drag", explain:"To move an object on a touchscreen or with a mouse.", phonetic:"[dræɡ]", image:"145.jpeg"},

    { num:146, word:"Encryption", explain:"The process of converting information into a secure code to protect it from unauthorized access.", phonetic:"[ɪnˈkrip.ʃən]", image:"146.jpeg"},
    { num:147, word:"Error Handling", explain:"Managing and addressing errors that occur during the execution of a program.", phonetic:"[ˈer.ər ˈhænd.lɪŋ]", image:"147.jpeg"},
    { num:148, word:"Event", explain:"An action that occurs in a system or program.", phonetic:"[ɪˈvent]", image:"148.png"},
    { num:149, word:"Exception Handling", explain:"The process of managing and responding to unexpected events or errors in software.", phonetic:"[ɪkˈsep.ʃən ˈhænd.lɪŋ]", image:"149.png"},
    { num:150, word:"Extract", explain:"To obtain data from one source and store it in another location.", phonetic:"[ɪkˈstrækt]", image:"150.jpeg"},

    { num:151, word:"Firewall configuration", explain:"Setting up security measures to control incoming and outgoing network traffic.", phonetic:"[ˈfaɪə.wɔːl kənˌfɪɡ.əˈreɪ.ʃən]", image:"151.jpeg"},
    { num:152, word:"Flesh out", explain:"To expand or complete details of a plan or idea.", phonetic:"[fleʃ aʊt]", image:"152.png"},
    { num:153, word:"Floppy disk", explain:"An outdated portable magnetic storage device.", phonetic:"[ˈflɒp.i dɪsk]", image:"153.jpeg"},
    { num:154, word:"Flowchart", explain:"A graphical representation of the steps in a process.", phonetic:"[ˈfləʊ.tʃɑːt]", image:"154.png"},
    { num:155, word:"Fluid design", explain:"A web design that automatically adapts to different screen sizes.", phonetic:"[ˈfluː.ɪd dɪˈzaɪn]", image:"155.png"},
    { num:156, word:"FLUTTER", explain:"An open-source framework developed by Google for building native applications for mobile, web, and desktop from a single codebase, using the Dart programming language.", phonetic:"[ˈflatə]", image:"156.png"},
    { num:157, word:"Framework", explain:"A set of tools and libraries for developing software.", phonetic:"[ˈfreɪm.wɜːk]", image:"157.jpeg"},
    { num:158, word:"Frameworks", explain:"Pre-built structures and tools that provide a foundation for developing software applications.", phonetic:"[ˈfreɪm.wɜːks]", image:"158.jpeg"},
    { num:159, word:"Frontend development", explain:"Creating the user interface and user experience components of a software application.", phonetic:"[ˌfrʌnt.end dɪˈvel.əp.mənt]", image:"159.jpeg"},
    { num:160, word:"Frontend", explain:"The part of a website or application that is visible and interactive for the user.", phonetic:"[ˌfrʌnt.end]", image:"160.png"},
    { num:161, word:"Full-stack", explain:"Software development that encompasses both the frontend and backend.", phonetic:"[fʊl-stæk]", image:"161.png"},
    { num:162, word:"Function", explain:"A block of code that performs a specific task.", phonetic:"[ˈfʌŋk.ʃən]", image:"162.png"},
    { num:163, word:"Functional programming", explain:"A programming paradigm where computation is treated as the evaluation of mathematical functions, avoiding changing state and mutable data.", phonetic:"[ˈfʌŋk.ʃən.əl ˈprəʊ.ɡræm.ɪŋ]", image:"163.png"},

    { num:164, word:"Git", explain:"A distributed version control system for tracking changes in code.", phonetic:"[ɡɪt]", image:"164.png"},
    { num:165, word:"Github", explain:"A hosting platform for Git projects.", phonetic:"[ɡɪt hʌb]", image:"165.jpeg"},
    { num:166, word:"Gitlab", explain:"Similar to Github, a platform for hosting Git projects.", phonetic:"[ɡɪt læb]", image:"166.png"},
    { num:167, word:"Go", explain:"A modern programming language developed by Google.", phonetic:"[ɡəʊ]", image:"167.jpeg"},

    { num:168, word:"Hacker", explain:"A person with computer skills who uses them for unauthorized purposes.", phonetic:"[ˈhæk.ər]", image:"168.jpeg"},
    { num:169, word:"Hacking", explain:"The attempt to gain unauthorized access to a computer system or network.", phonetic:"[ˈhæk.ɪŋ]", image:"169.jpeg"},
    { num:170, word:"Hard drive", explain:"A magnetic storage device that stores data on a spinning disk.", phonetic:"[hɑːd draɪv]", image:"170.jpeg"},
    { num:171, word:"Hardware", explain:"The physical components of a computer system.", phonetic:"[ˈhɑːd.weər]", image:"171.jpeg"},
    { num:172, word:"HDMI", explain:"High-Definition Multimedia Interface. It is a digital interface to transmit audio and video data on the same cable. Most HDTVs, DVDs, Blu-rays, cable boxes, and game consoles have HDMI support.", phonetic:"[ˌeɪtʃ.diː.emˈaɪ]", image:"172.jpeg"},
    { num:173, word:"Headphones", explain:"An audio device that is worn over the ears.", phonetic:"[ˈhed.fəʊnz]", image:"173.jpeg"},
    { num:174, word:"Highlight", explain:"To emphasize or make something more visible.", phonetic:"[ˈhaɪ.laɪt]", image:"174.png"},
    { num:175, word:"Hosting", explain:"A service that provides space on a server to store web files.", phonetic:"[ˈhəʊstɪŋ]", image:"175.jpeg"},
    { num:176, word:"HTML", explain:"HyperText Markup Language defines the structure and content of web pages.", phonetic:"[ˌeɪtʃ.tiː.emˈel]", image:"176.jpeg"},
    { num:177, word:"HTTP", explain:"HyperText Transfer Protocol, the protocol for transferring data on the web.", phonetic:"[ˌeɪtʃ.tiː.tiːˈpiː]", image:"177.png"},
    { num:178, word:"Hyperlink", explain:"A link in an electronic document that takes you to another location.", phonetic:"[ˈhaɪ.pə.lɪŋk]", image:"178.jpeg"},

    { num:179, word:"Iaas", explain:"Infrastructure as a Service, a cloud computing model that provides infrastructure as a service.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"179.jpeg"},
    { num:180, word:"IDE", explain:"Integrated Development Environment, an environment for creating software.", phonetic:"[aɪˈdi]", image:"180.jpeg"},
    { num:181, word:"Incident management", explain:"The process of identifying, responding to, and resolving incidents or issues in a system.", phonetic:"[ˈɪn.sɪ.dənt ˈmæn.ɪdʒ.mənt]", image:"181.jpeg"},
    { num:182, word:"Incident response", explain:"Coordinated actions taken in response to a security incident or breach.", phonetic:"[ˈɪn.sɪ.dənt rɪˈspɒns]", image:"182.png"},
    { num:183, word:"Infrastructure", explain:"The physical and virtual components that form the basis of a computer system.", phonetic:"[ˈɪn.frəˌstrʌk.tʃər]", image:"183.png"},
    { num:184, word:"Input device", explain:"A device used to enter data into a computer system.", phonetic:"[ˈɪn.pʊt dɪˈvaɪs]", image:"184.jpeg"},
    { num:185, word:"Integration test", explain:"A test that verifies how different components of a system interact.", phonetic:"[ˌɪn.tɪˈɡreɪ.ʃən test]", image:"185.png"},
    { num:186, word:"Internal storage", explain:"The storage space on an electronic device.", phonetic:"[ɪnˈtɜː.nəl ˈstɔː.rɪdʒ]", image:"186.jpeg"},
    { num:187, word:"Intrusion detection", explain:"Detecting and responding to unauthorized access or security breaches.", phonetic:"[ɪnˈtruː.ʒən dɪˈtek.ʃən]", image:"187.png"},
    { num:188, word:"Involve", explain:"To include or make someone participate in something.", phonetic:"[ɪnˈvɒlv]", image:"188.png"},
    
    { num:189, word:"Java", explain:"A general-purpose object-oriented programming language.", phonetic:"[ˈdʒɑː.və]", image:"189.png"},
    { num:190, word:"JavaScript", explain:"A programming language that allows user interaction on web pages.", phonetic:"[ˈdʒɑː.və skrɪpt]", image:"190.png"},
    { num:191, word:"JSON", explain:"A lightweight data-interchange format used for easy data exchange between applications.", phonetic:"[ˈd͡ʒeɪsən]", image:"191.png"},

    { num:192, word:"Keyboard", explain:"An input device that allows you to type letters, numbers, and symbols.", phonetic:"[ˈkiː.bɔːd]", image:"192.jpeg"},

    { num:193, word:"Library", explain:"A collection of reusable code for performing specific tasks.", phonetic:"[ˈlaɪ.brər.i]", image:"193.jpeg"},
    { num:194, word:"Load balancing", explain:"Distributing network traffic evenly across multiple servers to ensure optimal performance.", phonetic:"[ləʊd ˈbæl.ən.sɪŋ]", image:"194.png"},
    { num:195, word:"Load test", explain:"Tests that verify the performance of a system under load.", phonetic:"[ləʊd ˈtest]", image:"195.jpeg"},
    { num:196, word:"Log", explain:"A file that records events and activities in a system.", phonetic:"[lɒɡ]", image:"196.jpeg"},
    { num:197, word:"Logging", explain:"Recording events, activities, or errors in a system for analysis and troubleshooting.", phonetic:"[ˈlɒɡ.ɪŋ]", image:"197.jpeg"},
    { num:198, word:"Loops", explain:"Sections of code that execute repeatedly until a condition is met.", phonetic:"[luːps]", image:"198.jpeg"},
    
    { num:199, word:"Manual input", explain:"The process of entering data into a computer system manually.", phonetic:"[ˈmæn.ju.əl ˈɪn.pʊt]", image:"199.jpeg"},
    { num:200, word:"Manual operation", explain:"The process of performing a task in a computer system manually.", phonetic:"[ˈmæn.ju.əl ˌɒp.ərˈeɪ.ʃən]", image:"200.png"},

    //avanzar en links
    { num:201, word:"Merge", explain:"To integrate two or more things into one.", phonetic:"[mɜːdʒ]", image:"201.png"},
    { num:202, word:"Microphone", explain:"A device that converts sound into an electrical signal.", phonetic:"[ˈmaɪ.krə.fəʊn]", image:"202.jpeg"},
    { num:203, word:"Microservices", explain:"An architectural style where an application is composed of small, independent services.", phonetic:"[ˈmaɪ.krə.sɜː.vɪs]", image:"203.png"},
    { num:204, word:"Middleware", explain:"Software that acts as an intermediary between different software components.", phonetic:"[ˈmɪd.əl.weər]", image:"204.png"},
    { num:205, word:"Mixin", explain:"A reusable piece of code that can be included in other classes.", phonetic:"[mɪksɪŋ]", image:"205.jpeg"},
    { num:206, word:"Mobile applications", explain:"Software designed to operate on mobile devices such as smartphones and tablets.", phonetic:"[ˈməʊ.baɪl ˌæp.lɪˈkeɪ.ʃəns]", image:"206.jpeg"},
    { num:207, word:"Mobile development", explain:"Creating apps for smartphones, tablets, and wearables.", phonetic:"[ˈməʊ.baɪl dɪˈvel.əp.mənt]", image:"207.jpeg"},
    { num:208, word:"Mobile OS", explain:"Operating system designed for mobile devices, e.g., Android.", phonetic:"[ˈməʊ.baɪl ɒs]", image:"208.png"},
    { num:209, word:"Modem", explain:"Modulates/demodulates signals for communication.", phonetic:"[ˈməʊ.dem]", image:"209png"},
    { num:210, word:"Monitor", explain:"Display to visualize computer output.", phonetic:"[ˈmɒn.ɪ.tər]", image:"210.jpeg"},
    { num:211, word:"Monitoring", explain:"Continuously observing and measuring the performance and behavior of a system.", phonetic:"[ˈmɒn.ɪ.tə.rɪŋ]", image:"211.jpeg"},
    { num:212, word:"Monolith", explain:"Large application with all functionalities.", phonetic:"[ˈmɒn.ə.lɪθ]", image:"212.png"},
    { num:213, word:"Mouse", explain:"Device to control the cursor on the screen.", phonetic:"[maʊs]", image:"213.jpeg"},
    { num:214, word:"MR", explain:"Can refer to 'Master Record,' a term commonly used in administrative settings to designate a document or system containing centralized and updated information about certain records.", phonetic:"[em ɑːr]", image:"214.jpeg"},
    { num:215, word:"MVP", explain:"Minimum viable product to validate an idea.", phonetic:"[ˌem.viːˈpiː]", image:"215.png"},

    { num:216, word:"Network bandwidth", explain:"The amount of data that can be transmitted in a given time.", phonetic:"[ˈnet.wɜːk ˈbænd.wɪtθ]", image:"216.jpeg"},
    { num:217, word:"Network security", explain:"Protecting a computer network infrastructure against unauthorized access and attacks.", phonetic:"[ˈnet.wɜːk sɪˈkjʊə.rə.ti]", image:"217.png"},
    { num:218, word:"NoSQL database", explain:"Stores data in a flexible format.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"218.png"},
    { num:219, word:"NPM", explain:"It stands for 'Node Package Manager,' a command-line tool used to install, manage, and share easily reusable JavaScript code packages (or modules).", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"219.jpeg"},

    { num:220, word:"Objective-C", explain:"Programming language for iOS and macOS.", phonetic:"[əbˈdʒek.tɪv siː]", image:"220.png"},
    { num:221, word:"Object-Oriented programming (OOP)", explain:"A programming paradigm that uses objects, which encapsulate data and behavior, for software development.", phonetic:"[ˈɒb.dʒɪkt ˈɔː.ri.en.tɪd ˈprəʊ.ɡræm.ɪŋ]", image:"221.png"},
    { num:222, word:"OEM", explain:"Original Equipment Manufacturer, it refers to companies that manufacture and package products for others, and also to companies that acquire a product or component and reuse it or incorporate it into another new product with their own brand.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"222.png"},
    { num:223, word:"Open source", explain:"Accessible and modifiable source code.", phonetic:"[ˈəʊ.pən sɔːs]", image:"223.jpeg"},
    { num:224, word:"Operators", explain:"Companies that provide telecommunications services.", phonetic:"[ˈɒp.ər.eɪ.tərs]", image:"224.png"},
    { num:225, word:"Organization chart", explain:"A diagram that shows the hierarchical structure of an organization.", phonetic:"[ˌɔː.ɡən.aɪˈzeɪ.ʃən tʃɑːt]", image:"225.png"},
    { num:226, word:"Outcome", explain:"Consequence of an action or process.", phonetic:"[ˈaʊt.kʌm]", image:"226.jpeg"},
    { num:227, word:"Output", explain:"Information or data produced by a system.", phonetic:"[ˈaʊt.pʊt]", image:"227.png"},
    
    { num:228, word:"PaaS", explain:"Platform to develop, deploy, and manage applications.", phonetic:"[pɑːs]", image:"228.png"},
    { num:229, word:"Penetration Testing", explain:"Simulating cyber-attacks to identify vulnerabilities and weaknesses in a system.", phonetic:"[ ˌpenɪˈtreɪʃən ˈtes.tɪŋ]", image:"229.jpeg"},
    { num:230, word:"Performance benchmark", explain:"Comparing the performance of different systems or software.", phonetic:"[pəˈfɔː.məns ˈbentʃ.mɑːk]", image:"230.png"},
    { num:231, word:"Performance Monitoring", explain:"Tracking and analyzing the performance of a system during its operation.", phonetic:"[pəˈfɔː.məns ˈmɒn.ɪ.tər]", image:"231.jpeg"},
    { num:232, word:"Performance Optimization", explain:"Improving the efficiency and speed of a software application.", phonetic:"[pəˈfɔː.məns ˌɒp.tɪ.maɪˈzeɪ.ʃən]", image:"232.jpeg"},
    { num:233, word:"Performance Test", explain:"Performance measurement under real load.", phonetic:"[pəˈfɔː.məns test]", image:"233.jpeg"},
    { num:234, word:"Perl", explain:"Versatile language for web development and system administration.", phonetic:"[pɜːl]", image:"234.jpeg"},
    { num:235, word:"PHP", explain:"Language for developing dynamic web applications.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"235.png"},
    { num:236, word:"Plugin", explain:"Module that adds functionalities to a program.", phonetic:"[ˈplʌɡ.ɪn]", image:"236.png"},
    { num:237, word:"Plugs", explain:"Connectors to connect devices.", phonetic:"[plʌɡs]", image:"237.jpeg"},
    { num:238, word:"Port", explain:"Logical connection for communication between devices.", phonetic:"[pɔːt]", image:"238.jpeg"},
    { num:239, word:"Predefined process", explain:"A set of steps established beforehand to guide a particular action or task.", phonetic:"[ˌpriː.dɪˈfaɪnd ˈprəʊ.ses]", image:"239.jpeg"},
    { num:240, word:"Preparation", explain:"The act of getting ready for something, often involving gathering necessary materials and information.", phonetic:"[ˌprep.ərˈeɪ.ʃən]]", image:"240.jpeg"},
    { num:241, word:"Printed document", explain:"A physical copy of a document with text and/or images, created using a printer.", phonetic:"[ˈprɪn.tɪd ˈdɒk.jə.mənt]", image:"241.png"},
    { num:242, word:"Printer", explain:"A device that produces printed documents from digital files.", phonetic:"[ˈprɪn.tər]", image:"242.jpeg"},
    { num:243, word:"Privilege management", explain:"Controlling and assigning specific privileges or permissions to users.", phonetic:"[ˈprɪv.əl.ɪdʒ ˈmæn.ɪdʒ.mənt]", image:"243.png"},
    { num:244, word:"Process", explain:"A series of actions or steps taken to achieve a specific outcome.", phonetic:"[ˈprəʊ.ses]" , image:"244.jpeg"},
    { num:245, word:"Program", explain:"A set of instructions that tells a computer how to perform a specific task.", phonetic:"[ˈprəʊ.ɡræm]" , image:"245.jpeg"},
    { num:246, word:"Programming language", explain:"A system of communication used to write programs for computers.", phonetic:"[ˈprəʊ.ɡræm.ɪŋ ˈlæŋ.ɡwɪdʒ]" , image:"246.jpeg"},
    { num:247, word:"Programming paradigm", explain:"A fundamental approach to software development, such as object-oriented or functional programming.", phonetic:"[ˈprəʊ.ɡræm.ɪŋ ˈpær.ə.daɪm]" , image:"247.jpeg"},
    { num:248, word:"Programming", explain:"The process of creating programs using programming languages.", phonetic:"[ˈprəʊ.ɡræm.ɪŋ]", image:"248.jpeg"},
    { num:249, word:"Progressive Web App (PWA)", explain:"A website that offers app-like features and functionality, accessible even offline.", phonetic:"[prəˈɡres.ɪv web æp]" , image:"249.jpeg"},
    { num:250, word:"Project Manager", explain:"A person responsible for planning, coordinating, and executing projects to achieve specific goals.", phonetic:"[ˈprɒdʒ.ekt ˈmæn.ɪ.dʒər]" , image:"250.jpeg"},
    { num:251, word:"Pseudocode", explain:"An informal, human-readable description of an algorithm, used for planning and understanding before writing actual code.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users" , image:"251.png"},
    { num:252, word:"Python", explain:"A general-purpose, interpreted programming language known for its readability and versatility.", phonetic:"[ˈpaɪ.θən]", image:"252.jpeg"},

    { num:253, word:"Quality Assurance", explain:"The systematic process of ensuring that a product or system meets specified requirements and quality standards.", phonetic:"[ˈkwɒl.ə.ti əˈʃɔː.rəns]", image:"253.jpeg"},

    { num:254, word:"R", explain:"A programming language and software environment for statistical computing and graphics.", phonetic:"[ɑːr]" , image:"254.jpeg"},
    { num:255, word:"RADIUS", explain:"Remote Authentication Dial In User Service. It is defined in RFC 2865, protocol for remote authentication. RADIUS allows centralized management of authentication data, such as username and passwords.", phonetic:"[ˈreɪ.di.əs]", image:"255.jpeg"},
    { num:256, word:"Recursion", explain:"A programming technique where a function calls itself within its own body.", phonetic:"[rɪˈkɜː.ʒən]" , image:"256.jpeg"},
    { num:257, word:"Refactoring Techniques", explain:"Methods for restructuring code to enhance its design and maintainability.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users" , image:"257.png"},
    { num:258, word:"Refactoring", explain:"The process of improving the structure and design of existing code without changing its functionality.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"258.jpeg"},
    { num:259, word:"Regression testing", explain:"The process of retesting previously working code after changes are made to ensure it still functions correctly.", phonetic:"[rɪˈɡreʃ.ən ˈtes.tɪŋ]" , image:"259.png"},
    { num:260, word:"Regulations", explain:"Official rules or directives governing the development and use of software.", phonetic:"[ˌreɡ.jəˈleɪ.ʃəns]" , image:"260.jpeg"},
    { num:261, word:"Regulatory compliance", explain:"Ensuring that software development and operations comply with relevant laws and regulations.", phonetic:"[ˌreɡ.jəˈleɪ.tər.i kəmˈplaɪ.əns]" , image:"261.png"},
    { num:262, word:"Relational database", explain:"A type of database that organizes data in tables with rows and columns, where rows represent records and columns represent attributes of those records.", phonetic:"[rɪˈleɪ.ʃən.əl ˈdeɪ.tə.beɪs]", image:"262.png"},
    { num:263, word:"RENDER", explain:"In the context of computing and graphics, it refers to the process of generating an image from a three-dimensional model using rendering software.", phonetic:"[ˈren.dər]" , image:"263.jpeg"},
    { num:264, word:"Repeat", explain:"The act of performing an action multiple times, either a specific number of times or until a certain condition is met.", phonetic:"[rɪˈpiːt]" , image:"264.jpeg"},
    { num:265, word:"Repository", explain:"A storage location for version-controlled code and related assets.", phonetic:"[rɪˈpɒz.ɪ.tər.i]" , image:"265.png"},
    { num:266, word:"Responsive Design", explain:"Designing applications or websites that adapt to different screen sizes and devices.", phonetic:"[rɪˈspɒn.sɪv dɪˈzaɪn]", image:"266.jpeg"},
    { num:267, word:"REST", explain:"An architectural style for web APIs based on HTTP requests and responses.", phonetic:"[rest]" , image:"267.png"},
    { num:268, word:"Rich Media", explain:"Media technology which has been developed to deliver interactive multimedia or expanded creative space to users.", phonetic:"[rɪtʃ ˈmiː.di.ə]", image:"268.png"},
    { num:269, word:"Risk Assessment", explain:"Evaluating potential risks and vulnerabilities to determine their impact.", phonetic:"[rɪsk əˈses.mənt]" , image:"269.jpeg"},
    { num:270, word:"Risk Management", explain:"Developing strategies to mitigate and control risks within an organization.", phonetic:"[rɪsk ˈmæn.ɪdʒ.mənt]" , image:"270.png"},
    { num:271, word:"Ruby", explain:"A general-purpose, interpreted programming language known for its elegance and readability.", phonetic:"[ˈruː.bi]", image:"271.png"},

    { num:272, word:"SaaS (Software as a Service)", explain:"A cloud-based software delivery model where users access applications over the internet instead of installing them locally.", phonetic:"[ˈsɒft.weər æz eɪ ˈsɜː.vɪs]" , image:"272.jpeg"},
    { num:273, word:"SASS", explain:"A preprocessor for writing CSS stylesheets, making them more maintainable and readable.", phonetic:"[sæs]" , image:"273.jpeg"},
    { num:274, word:"Scala", explain:"A general-purpose, object-functional programming language known for its scalability and expressiveness.", phonetic:"[ˈskaːla]" , image:"274.png"},
    { num:275, word:"Scalability", explain:"The ability of a system or application to handle increased load or demand.", phonetic:"[ˌskeɪ.ləˈbɪl.ə.ti]", image:"275.jpeg"},
    { num:276, word:"Scanner", explain:"A device that captures images or data electronically, often used for documents or barcodes.", phonetic:"[ˈskæn.ər]" , image:"276.jpeg"},
    { num:277, word:"Scripting", explain:"Writing code to automate tasks or processes in a script or program.", phonetic:"[skrɪpt.ɪŋ]" , image:"277.jpeg"},
    { num:278, word:"Scroll", explain:"The act of moving vertically or horizontally within a window or on a screen.", phonetic:"[skrəʊl]" , image:"278.jpeg"},
    { num:279, word:"Scrum Master", explain:"A person who facilitates and guides a Scrum team, ensuring they follow the process effectively.", phonetic:"[skrʌm ˈmɑː.stər]", image:"279.png"},
    { num:280, word:"Scrum", explain:"An agile project management framework that uses short sprints, daily stand-ups, and retrospectives.", phonetic:"[skrʌm]" , image:"280.jpeg"},
    { num:281, word:"SD card (Secure Digital card)", explain:"A removable flash memory card used for storing data in devices like cameras and smartphones.", phonetic:"[sɪˈkjʊər ˈdɪdʒ.ɪ.təl kɑːd]" , image:"281.jpeg"},
    { num:282, word:"Secure Coding practices", explain:"Adhering to coding practices that prioritize security and reduce vulnerabilities.", phonetic:"[sɪˈkjʊər kəd.ɪŋ ˈpræk.tɪs]" , image:"282.jpeg"},
    { num:283, word:"Secure Coding", explain:"Writing code with security considerations to prevent vulnerabilities.", phonetic:"[sɪˈkjʊər kəd.ɪŋ]", image:"283.jpeg"},
    { num:284, word:"Secure Communication", explain:"Ensuring that data transmission between systems is confidential and tamper-proof.", phonetic:"[sɪˈkjʊər kəˌmjuː.nɪˈkeɪ.ʃən]" , image:"284.jpeg"},
    { num:285, word:"Secure Configuration management", explain:"Ensuring that systems and software are configured securely to minimize risks.", phonetic:"[sɪˈkjʊər kənˌfɪɡ.əˈreɪ.ʃən ˈmæn.ɪdʒ.mənt]" , image:"285.jpeg"},
    { num:286, word:"Secure deployment", explain:"Implementing security measures when deploying software to production.", phonetic:"[sɪˈkjʊər dɪˈplɔɪ.mənt]", image:"286.png"},
    { num:287, word:"Secure design principles", explain:"Fundamental principles for designing secure software applications.", phonetic:"[sɪˈkjʊər dɪˈzaɪn ˈprɪn.sə.pəls]" , image:"287.png"},
    { num:288, word:"Secure development frameworks", explain:"Established structures and tools that prioritize security in software development.", phonetic:"[sɪˈkjʊər dɪˈvel.əp.mənt ˈfreɪm.wɜːks]" , image:"288.jpeg"},
    { num:289, word:"Secure DevOps", explain:"Integrating security practices into the DevOps process to create a secure software development pipeline.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users", image:"289.jpeg"},
    { num:290, word:"Secure software development lifecycle (SDLC)", explain:"Integrating security into every phase of the software development process.", phonetic:"[sɪˈkjʊər ˈsɒft.weər dɪˈvel.əp.mənt ˈlaɪf ˌsaɪ.kəl]" , image:"290.jpeg"},
    { num:291, word:"Security measures", explain:"Strategies and implementations to safeguard software and data from unauthorized access and threats.", phonetic:"[sɪˈkjʊə.rə.ti ˈmeʒ.ər]", image:"291.jpeg"},
    { num:292, word:"Security operations center (SOC)", explain:"A centralized unit responsible for monitoring and managing security incidents.", phonetic:"[sɪˈkjʊə.rə.ti ˌɒpərˈeɪʃənz ˈsen.tər]" , image:"292.jpeg"},
    { num:293, word:"Security Policies", explain:"Guidelines and rules defining the organization's approach to information security.", phonetic:"[sɪˈkjʊə.rə.ti ˈpɒl.ə.si]" , image:"293.jpg"},
    { num:294, word:"Security Standards", explain:": Established criteria and benchmarks for maintaining security in software and systems.", phonetic:"[sɪˈkjʊə.rə.ti ˈstæn.dəds]", image:"294.jpeg"},
    { num:295, word:"Security testing", explain:"Assessing the security aspects of a system to identify vulnerabilities and weaknesses.", phonetic:"[sɪˈkjʊə.rə.ti ˈtes.tɪŋ]", image:"295.jpeg"},
    { num:296, word:"Sequencing", explain:"The act of arranging things in a specific order or sequence.", phonetic:"[ˈsiː.kwən.sɪŋ]", image:"296.png"},
    { num:297, word:"Server", explain:"A computer that provides services to other computers over a network, such as websites, emails, and files.", phonetic:"[ˈsɜː.vər]" , image:"297.jpeg"},
    { num:298, word:"Server-side Scripting", explain:"Executing scripts on the server to generate dynamic web content.", phonetic:"[ˈsɜː.vər saɪd skrɪpt.ɪŋ]", image:"298.png"},
    { num:299, word:"Setting up", explain:"The process of configuring or preparing something for use.", phonetic:"[ˈset.ɪŋ ʌp]" , image:"299.jpeg"},
    { num:300, word:"Shell", explain:"A command-line interface for interacting with a computer operating system.", phonetic:"[ʃel]" , image:"300.png"},
    { num:301, word:"Smoke test", explain:"A basic test to quickly verify if a system or application is functioning at a minimum level.", phonetic:"[sməʊk test]", image:"301.jpeg"},
    { num:302, word:"SOAP (Simple Object Access Protocol)", explain:"A protocol for exchanging information between applications using XML and web services.", phonetic:"[səʊp]" , image:"302.png"},
    { num:303, word:"Software bug", explain:"An error in software code causing issues.", phonetic:"[ˈsɒft.weər bʌɡ]", image:"303.jpeg"},
    { num:304, word:"Software containers", explain:"Packaging software with all dependencies for easy deployment.", phonetic:"[ˈsɒft.weər]", image:"304.jpeg"},
    { num:305, word:"Software engineering", explain:"The systematic application of engineering principles to the design, development, testing, and maintenance of software.", phonetic:"[ˈsɒft.weər ˌen.dʒɪˈnɪə.rɪŋ]" , image:"305.jpeg"},
    { num:306, word:"software testing", explain:"The process of evaluating and validating software to ensure it meets requirements and operates as expected.", phonetic:"[ˈsɒft.weər ˈtes.tɪŋ]", image:"306.png"},
    { num:307, word:"Software", explain:"A collection of instructions that tell a computer how to perform specific tasks.", phonetic:"[ˈsɒft.weər]" , image:"307.jpeg"},
    { num:308, word:"SOLID principles", explain:"A set of object-oriented design principles for creating maintainable and flexible software.", phonetic:"[ˈsɒl.ɪd ˈprɪn.sə.pəls]" , image:"308.jpeg"},
    { num:309, word:"Sort", explain:"The process of arranging items in a specific order, such as numerically or alphabetically.", phonetic:"[sɔːt]", image:"309.jpeg"},
    { num:310, word:"Source code", explain:"Human-readable instructions written by a programmer.", phonetic:"[sɔːs kəʊd]", image:"310.jpeg"},
    { num:311, word:"Source", explain:"The origin of something, such as data, code, or information.", phonetic:"[sɔːs]" , image:"311.jpeg"},
    { num:312, word:"Speakers", explain:"Devices that produce sound, often used for listening to music, movies, or other audio content.", phonetic:"[ˈspiː.kərs]", image:"312.jpeg"},
    { num:313, word:"SQL (Structure Query Language)", explain:"A language for interacting with relational databases.", phonetic:"[ˈstrʌk.tʃər ˈkwɪə.ri ˈlæŋ.ɡwɪdʒ]", image:"313.jpeg"},
    { num:314, word:"SSL (Secure Sockets Layer)", explain:"A security protocol that encrypts data transmitted over the internet, protecting it from eavesdropping and tampering.", phonetic:"[sɪˈkjʊər ˈsɒk.ɪts ˈleɪ.ər]" , image:"314.jpeg"},
    { num:315, word:"Steps", explain:"A sequence of actions taken to achieve a goal.", phonetic:"[steps]", image:"315.jpeg"},
    { num:316, word:"Storage device", explain:"A device used to store data, such as a hard drive, SSD, or USB drive.", phonetic:"[ˈstɔː.rɪdʒ dɪˈvaɪs]" , image:"316.jpeg"},
    { num:317, word:"Storage", explain:"The act of saving or keeping data for future use.", phonetic:"[ˈstɔː.rɪdʒ]" , image:"317.jpg"},
    { num:318, word:"Stored data", explain:"Data that has been saved for future use.", phonetic:"[stɔːrd ˈdeɪ.tə]", image:"318.jpeg"},
    { num:319, word:"Stress tests", explain:"Tests that are designed to push a system or application to its limits to identify potential failures.", phonetic:"[stres tests]" , image:"319.jpeg"},
    { num:320, word:"Subversion", explain:"A version control system that allows users to track changes to files and folders.", phonetic:"[səbˈvɜː.ʃən]", image:"320.jpeg"},
    { num:321, word:"Swift", explain:"It is a programming language developed by Apple for creating applications for iOS, macOS, watchOS, and tvOS. It is known for its concise syntax and focus on safety and performance.", phonetic:"[swɪft]" , image:"321.jpeg"},
    { num:322, word:"SysAdmin", explain:"A system administrator, responsible for the maintenance and operation of computer systems.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users" , image:"322.jpeg"},
    { num:323, word:"System connector", explain:"A component linking different parts of a system or program.", phonetic:"[ˈsɪs.təm kəˈnek.tər]", image:"323.jpeg"},

    { num:324, word:"Task", explain:"A unit of work that needs to be completed.", phonetic:"[tɑːsk]" , image:"324.jpeg"},
    { num:325, word:"Technical Debt", explain:"Accumulated compromises in code quality that may require future attention.", phonetic:"[ˈtek.nɪ.kəl det]" , image:"325.jpeg"},
    { num:326, word:"Terminator", explain:"A program that terminates other programs.", phonetic:"[ˈtɜː.mɪ.neɪ.tər]" , image:"326.jpeg"},
    { num:327, word:"Test Automation", explain:"Running tests automatically using software.", phonetic:"[test ˌɔː.təˈmeɪ.ʃən]", image:"327.jpeg"},
    { num:328, word:"Test Cases", explain:"Specific conditions or scenarios designed to verify the functionality of a software application.", phonetic:"[test keɪs]" , image:"328.jpeg"},
    { num:329, word:"Test Coverage", explain:"The extent to which a system has been tested, measured by the percentage of code or functionality covered.", phonetic:"[test ˈkʌv.ər.ɪdʒ]" , image:"329.jpeg"},
    { num:330, word:"Test Execution", explain:"Running the tests to evaluate the behavior and performance of a software application.", phonetic:"[test ˌek.sɪˈkjuː.ʃən]" , image:"330.jpeg"},
    { num:331, word:"Test Metrics", explain:"Quantifiable measures used to assess the effectiveness and progress of testing activities.", phonetic:"[test ˈmetrɪks]", image:"331.jpeg"},
    { num:332, word:"Test Plan", explain:"A comprehensive document outlining the testing approach, scope, resources, and schedule.", phonetic:"[test plæn]" , image:"332.jpeg"},
    { num:333, word:"Test Results", explain:"The outcomes and findings from the execution of software tests.", phonetic:"[test rɪˈzʌlts]" , image:"333.jpeg"},
    { num:334, word:"Test Strategy", explain:"The overall plan for testing, including the scope, resources, and testing methods.", phonetic:"[test ˈstræt.ə.dʒi]" , image:"334.jpeg"},
    { num:335, word:"Test Suites", explain:"A collection of test cases that are executed together to validate different aspects of a system.", phonetic:"[test swiːt]", image:"335.jpeg"},
    { num:336, word:"Tester", explain:"A person who tests software to ensure it meets requirements and operates as expected.", phonetic:"ˈtes.tər]" , image:"336.jpeg"},
    { num:337, word:"Text editor", explain:"A program used to create and edit text files.", phonetic:"[tekst ˈed.ɪ.tər]" , image:"337.jpeg"},
    { num:338, word:"Text-based interface", explain:"Interaction with a computer through text.", phonetic:"[tekst-beɪst ˈɪn.tə.feɪs]", image:"338.jpeg"},
    { num:339, word:"The call", explain:"The act of making a phone call or using a communication service.", phonetic:"[ðiː kɔːl]" , image:"339.jpeg"},
    { num:340, word:"Threat intelligence", explain:"Gathering and analyzing information about potential cybersecurity threats.", phonetic:"[θret ɪnˈtel.ɪ.dʒəns]" , image:"340.png"},
    { num:341, word:"Threat modeling", explain:"Identifying potential security threats and planning countermeasures during the design phase.", phonetic:"[θret ˈmɒd.əl.ɪŋ]", image:"341.jpeg"},
    
    { num:342, word:"UI (User Interface)", explain:"The part of a software application that users interact with.", phonetic:"[ˌjuːˈaɪ]" , image:"342.jpeg"},
    { num:343, word:"Unauthorized access", explain:" Illegitimate entry into a system or network.", phonetic:"[ʌnˈɔː.θə.raɪzd ˈæk.ses]" , image:"343.jpeg"},
    { num:344, word:"Unit test", explain:"Tests that are designed to test individual units of code, such as functions or methods.", phonetic:"[ˈjuː.nɪt test]" , image:"344.jpeg"},
    { num:345, word:"Until", explain:"A conjunction used to indicate a point in time before which something will happen.", phonetic:"[ənˈtɪl]", image:"345.jpeg"},
    { num:346, word:"Usability", explain:"The ease with which a user can use a product or service.", phonetic:"[ˌjuːzəˈbɪləti]" , image:"346.jpeg"},
    { num:347, word:"USB Flash Drive", explain:"A portable storage device that uses flash memory.", phonetic:"[ˌjuː.esˈbiː flæʃ draɪv]" , image:"347.jpeg"},
    { num:348, word:"User Authentication", explain:"Verifying the identity of users accessing a system.", phonetic:"[ˈjuː.zər ɔːˌθen.tɪˈkeɪ.ʃən]" , image:"348.jpeg"},
    { num:349, word:"User Authorization", explain:"Granting or restricting access rights to users based on their roles or permissions.", phonetic:"[ˈjuː.zər ˌɔː.θər.aɪˈzeɪ.ʃən]", image:"349.jpeg"},
    { num:350, word:"UX (User Experience)", explain:"The overall experience of using a product or service.", phonetic:"[ˌjuːˈeks]" , image:"350.jpeg"},
    
    { num:351, word:"Variables", explain:"Named locations in memory that store data.", phonetic:"[ˈveə.ri.ə.bəls]" , image:"351.png"},
    { num:352, word:"Version Control", explain:"Managing changes in software code over time.", phonetic:"[ˈvɜː.ʃən kənˈtrəʊl]" , image:"352.jpeg"},
    { num:353, word:"Visual Basic .Net", explain:"A programming language that allows users to create Windows applications.", phonetic:"[ˈvɪʒ.u.əl ˈbeɪ.sɪk net]" , image:"353.jpeg"},
    { num:354, word:"VITE", explain:"It could refer to 'life' in various languages, but in some technical contexts, it might be an abbreviation for 'Vue.js Integrated Template Engine,' an integrated template engine for Vue.js, a JavaScript framework.", phonetic:"[vit]", image:"354.jpeg"},
    { num:355, word:"Vulnerability Management", explain:"Identifying, prioritizing, and addressing vulnerabilities in a systematic way.", phonetic:"[ˌvʌl.nər.əˈbɪl.ə.ti ˈmæn.ɪdʒ.mənt]" , image:"355.jpeg"},
    { num:356, word:"Vulnerability Scanning", explain:"Identifying and assessing potential vulnerabilities in a system.", phonetic:"[ˌvʌl.nər.əˈbɪl.ə.ti skæn.nɪŋ]" , image:"356.jpeg"},
    
    { num:357, word:"Web Applications", explain:"Applications accessed and operated through web browsers.", phonetic:"[web ˌæp.lɪˈkeɪ.ʃəns]" , image:"357.jpeg"},
    { num:358, word:"Web browser", explain:"Software used to access and navigate websites.", phonetic:"[web ˈbraʊ.zər]" , image:"358.jpeg"},
    { num:359, word:"Webhook", explain:"A way for an app to provide other applications with real-time information.", phonetic:"[ˈwɛb.hʊk]" , image:"359.png"},
    { num:360, word:"While loop", explain:"A programming loop that repeats a block of code until a condition is met.", phonetic:"[waɪl luːp]", image:"360.jpeg"},

];
export {glosary};