const glosary=[
    { num:1, word:"Acceptance criteria", explain:"Conditions that a system must meet to be accepted by a user or stakeholders.", phonetic:"[əkˈseptənts kraɪˈtɪərɪə]"},
    { num:2, word:"Acceptance tests", explain:"Confirm that system meets user requirements before final deployment.", phonetic:"[əkˈseptənts ˈtest]"},
    { num:3, word:"Access Control", explain:"Managing and regulating access to resources or systems.", phonetic:"[ˈækses kənˈtrəʊl]"},
    { num:4, word:"Acts", explain:"Individual commands in a script or program.", phonetic:"[ˈækts]"},
    { num:5, word:"Adaptive design", explain:"Adjusts website layout to different screen sizes.", phonetic:"[əˈdæp.tɪv dɪˈzaɪn]"},
    { num:6, word:"Adjustment", explain:"A minor change made to a system or process / Small change to system or process.", phonetic:"[əˈdʒʌst.mənt]"},
    { num:7, word:"Agile methodology", explain:"An iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˌmeθ.əˈdɒl.ə.dʒi]"},
    { num:8, word:"Agile software development", explain:"Iterative and flexible approach to software development.", phonetic:"[ˈædʒ.aɪl ˈsɒft.weər dɪˈvel.əp.mənt]"},
    { num:9, word:"AI", explain:"Artificial Intelligence, a branch of computer science that seeks to create intelligent systems.", phonetic:"[ˌeɪˈaɪ]"},
    { num:10, word:"AJAX", explain:"Technique for asynchronous web page updates.", phonetic:"[ˈeɪʤæks]"},
    { num:11, word:"Algorithm", explain:"Set of instructions for solving a problem.", phonetic:"[ˈæl.ɡə.rɪ.ðəm]"},
    { num:12, word:"Algorithmic solution", explain:"A set of step-by-step instructions to solve a specific problem.", phonetic:"[ˌæl.ɡəˈrɪð.mɪk səˈluː.ʃən]"},
    { num:13, word:"Analysis", explain:"The process of examining and breaking down a complex system or problem into smaller parts to understand its components and relationships.", phonetic:"[əˈnæl.ə.sɪs]"},
    { num:14, word:"Android", explain:"Mobile operating system developed by Google.", phonetic:"[ˈæn.drɔɪd]"},
    { num:15, word:"API integration", explain:"Connecting different software components to enable communication.", phonetic:"[ˌeɪ.piˈaɪ ˌɪn.tɪˈɡreɪ.ʃən]"},
    { num:16, word:"API", explain:"Interface for software components to interact. ", phonetic:"[ˌeɪ.piˈaɪ]"},
    { num:17, word:"Architecture", explain:"The high-level structure or design of a system, defining its components and their interactions to achieve specific objectives", phonetic:"[ˈɑː.kɪ.tek.tʃər]"},
    { num:18, word:"ASCII", explain:"Code that numerically represents a character, such as 'a' or '@.'.", phonetic:"[ˈæs.ki]"},
    { num:19, word:"Asynchronouns", explain:"A technique where tasks operate independently and don't wait for each other to complete.", phonetic:"[eɪˈsɪŋkrənəs]"},
    { num:20, word:"Authentication", explain:"Verifying the identity of a user or system to ensure secure access.", phonetic:"[ɔːˌθen.tɪˈkeɪ.ʃən]"},
    { num:21, word:"Authorization", explain:"Granting appropriate access rights to users or systems based on their authenticated identity.", phonetic:"[ˌɔː.θər.aɪˈzeɪ.ʃən]"},
    { num:22, word:"Automated test", explain:"Test run automatically by software.", phonetic:"[ˈɔː.tə.meɪ.tɪd ˈtest]"},

    { num:23, word:"Backdoor", explain:"Unauthorized access point to a system. ", phonetic:"[ˈbæk.dɔːr]"},
    { num:24, word:"Backend Development", explain:"Writing server-side logic and handling database interactions to support the functionality of a software application.", phonetic:"[ˌbæk.end dɪˈvel.əp.mənt]"},
    { num:25, word:"Backup", explain:"Copy of data used for recovery in case of loss.", phonetic:"[ˌˈbæk.ʌp]"},
    { num:26, word:"Bandwidth", explain:"Amount of data transferrable in a given time. ", phonetic:"[ˈbænd.wɪtθ]"},
    { num:27, word:"Batch", explain:"It is a file that chains commands that are carried out by the PC when it is invoked.", phonetic:"[bætʃ]"},
    { num:28, word:"BCC", explain:"BCC is the acronym for 'Blind Carbon Copy'.", phonetic:"[ˌbiːsiːˈsiː]"},
    { num:29, word:"Benchmarking", explain:"Comparing performance of different systems or software. ", phonetic:"[ˈbentʃˌmɑː.kɪŋ]"},
    { num:30, word:"Big data analytics", explain:"Analyzing large and complex datasets for insights.", phonetic:"[bɪɡ ˈdeɪ.tə ˌæn.əlˈɪt.ɪks]"},
    { num:31, word:"Big data", explain:"Large and complex datasets requiring specialized processing. ", phonetic:"[bɪɡ ˈdeɪ.tə]"},
    { num:32, word:"Binary code", explain:"Machine-readable code using 0s and 1s. ", phonetic:"[ˈbaɪ.nər.i kəʊd]"},
    { num:33, word:"Binary digit (Bit)", explain:"The smallest unit of data storage, either 0 or 1.", phonetic:"[ˈbaɪ.nər.i ˈdɪdʒ.ɪt]"},
    { num:34, word:"Binary large object (BLOB)", explain:"Storing data without a specific format.", phonetic:"[ˈbaɪ.nər.i lɑːdʒ ˈɒb.dʒɪkt]"},
    { num:35, word:"Binary representation", explain:"Binary representation is a way of representing data using only two states or values: 0s and 1s. It is used by computers and other digital systems to encapsulate and manipulate numerical values.", phonetic:"[ˈbaɪ.nər.i ˌrep.rɪ.zenˈteɪ.ʃən]"},
    { num:36, word:"BIOS initialization", explain:"Basic Input/Output System starting hardware during computer startup.", phonetic:"[ˈbaɪ.ɒs ɪˈnɪʃ.əl.aɪz]"},
    { num:37, word:"BIOS", explain:"Basic input/output system, initializes hardware during startup.", phonetic:"[ˈbaɪ.ɒs]"},
    { num:38, word:"Bitbucket", explain:"Software development platform similar to GitHub.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:39, word:"BLOB", explain:"Binary large object, data stored without specific format.", phonetic:"[blɒb]"},
    { num:40, word:"Blockchain technology", explain:"A secure digital ledger using cryptographic techniques.", phonetic:"[ˈblɒk.tʃeɪn tekˈnɒl.ə.dʒi]"},
    { num:41, word:"Blockchain", explain:"Digital ledger of transactions secured through cryptography.", phonetic:"[ˈblɒk.tʃeɪn]"},
    { num:42, word:"Boot", explain:"Starting up a computer or device.", phonetic:"[buːt]"},
    { num:43, word:"Bootstrap", explain:"Front-end framework for web development. ", phonetic:"[ˈbuːt.stræp]"},
    { num:44, word:"Bootstrapping", explain:"Self-starting a computer or device. ", phonetic:"[ˈbuːtˌstræpɪŋ]"},
    { num:45, word:"Botnet network", explain:"A network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net ˈnet.wɜːk]"},
    { num:46, word:"Botnet", explain:"Network of compromised computers controlled remotely.", phonetic:"[ˈbɒt.net]"},
    { num:47, word:"Branch", explain:"Different versions of code within a single project.", phonetic:"[brɑːntʃ]"},
    { num:48, word:"Breakpoint", explain:"Pause execution of program to debug.", phonetic:"[ˈbreɪkpɔɪnt]"},
    { num:49, word:"Browser", explain:"Software used to access websites.", phonetic:"[ˈbraʊ.zər]"},
    { num:50, word:"Bug", explain:"Error in software code causing issues.", phonetic:"[bʌɡ]"},
    { num:51, word:"Business analysis", explain:"Analyzing business needs and translating them into technical requirements.", phonetic:"[ˈbɪz.nɪs əˈnæl.ə.sɪs]"},
    { num:52, word:"Business continuity", explain:"Planning and processes to ensure that critical business functions can continue in the face of disruptions.", phonetic:"[ˈbɪz.nɪs ˌkɒn.tɪˈnjuː.ə.ti]"},
    { num:53, word:"Byte storage", explain:"The basic unit of information in computer storage and processing. A byte consists of 8 adjacent binary digits (bits), each of which consists of a 0 or 1.", phonetic:"[baɪt ˈstɔː.rɪdʒ]"},
    { num:54, word:"Byte", explain:"Group of 8 bits, basic unit of memory and storage.", phonetic:"[baɪt]"},
    
    { num:55, word:"C#", explain:"Object-oriented programming language developed by Microsoft.", phonetic:"[siː] /chart/"},
    { num:56, word:"C", explain:"General-purpose programming language.", phonetic:"[siː]"},
    { num:57, word:"C++", explain:"General-purpose programming language based on C.", phonetic:"[siː] /plus plus/"},
    { num:58, word:"Cache", explain:"Copy that a computer maintains of the recently visited web pages, if the user requests them, they are read from the hard drive without having to connect to the network again; thus, achieving a very noticeable improvement in speed.", phonetic:"[kæʃ]"},
    { num:59, word:"Captcha", explain:"Completely Automated Public Turing, or Completely Automated Public Turing. It is a small test that helps determine whether a user is a computer or a human.", phonetic:"[ˈkæp.tʃə]"},
    { num:60, word:"Carriers", explain:"Telecommunications operators who own the Internet backbone networks and are responsible for data transport.", phonetic:"[ˈkær.i.ərs]"},
    { num:61, word:"Cascading Style Sheets (CSS)", explain:"Defines the visual style of web pages.", phonetic:"[ˌsiː.esˈes] or [kæsˌkeɪ.dɪŋ ˈstaɪl ˌʃiːt]"},
    { num:62, word:"CD", explain:"Compact disc for storing data.", phonetic:"[ˌsiːˈdiː]"},
    { num:63, word:"CD-RW", explain:"Rewritable compact disc, which can be written, erased and rewritten over.", phonetic:"[ˌsiː.diː.ɑːˈdʌb.əl.juː]"},
    { num:64, word:"Central processing unit (CPU)", explain:"The main brain of a computer.", phonetic:"[ˈsen.trəl ˈprəʊ.ses.ɪŋ ˈjuː.nɪt]"},
    { num:65, word:"Client-Side Scripting", explain:"Executing scripts on the user's browser to enhance interactivity.", phonetic:"[ˈklaɪ.ənt-saɪd skrɪp.tɪŋ]"},
    { num:66, word:"Cloud computing", explain:"Accessing services over the internet instead of locally.", phonetic:"[klaʊd kəmˈpjuː.tɪŋ]"},
    { num:67, word:"Cloud service", explain:"Services accessed over the internet instead of being hosted locally.", phonetic:"[klaʊd ˈsɜː.vɪs]"},
    { num:68, word:"Cluster", explain:"Hard drive storage unit. ", phonetic:"[ˈklʌs.tər]"},
    { num:69, word:"Code branching", explain:"Creating different versions of code within a single project.", phonetic:"[kəʊd brɑːnt.ʃɪŋ]"},
    { num:70, word:"Code compilation", explain:"Translating programming code into machine-readable instructions.", phonetic:"[kəʊd ˌkɒm.pɪˈleɪ.ʃən]"},
    { num:71, word:"Code declaration", explain:"Specifying a variable, function, or other entity in code.", phonetic:"[kəʊd ˌdek.ləˈreɪ.ʃən]"},
    { num:72, word:"Code refactoring", explain:"Restructuring existing code to improve its readability, maintainability, and efficiency.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:73, word:"Code review", explain:"The systematic examination of source code to find and fix issues, ensure quality, and share knowledge among team members.", phonetic:"[kəʊd rɪˈvjuː]"},
    { num:74, word:"Code smells", explain:"Indicators of potential issues in code, suggesting the need for refactoring.", phonetic:"[kəʊd smels]"},
    { num:75, word:"Code ", explain:"Set of instructions for a computer to execute.", phonetic:"[kəʊd]"},
    { num:76, word:"Command execution ", explain:"Issuing instructions to a system or program.", phonetic:"[kəˈmɑːnd ˌek.sɪˈkjuː.ʃən]"},
    { num:77, word:"Command", explain:"Instruction given to a system or program. ", phonetic:"[kəˈmɑːnd]"},
    { num:78, word:"Commit", explain:"Submitting changes to a version control system like Git. ", phonetic:"[kəˈmɪt]"},
    { num:79, word:"Compact disc storage", explain:"Storage medium for data. ", phonetic:"[kəmˈpækt dɪsk ˈstɔː.rɪdʒ]"},
    { num:80, word:"Compatibility testing", explain:"Ensuring software works on different systems. ", phonetic:"[kəmˌpæt.əˈbɪl.ə.ti ˈtes.tɪŋ]"},
    { num:81, word:"Compiler", explain:"Translates programming code into machine-readable instructions.  ", phonetic:"[kəmˈpaɪ.lər]"},
    { num:82, word:"Compliance audits", explain:"Evaluations to ensure that software processes and practices adhere to established standards and regulations.  ", phonetic:"[kəmˈplaɪ.əns ˈɔː.dɪt]"},
    { num:83, word:"Compliance", explain:"Adhering to laws, regulations, and industry standards relevant to software development and operation.  ", phonetic:"[kəmˈplaɪ.əns]"},
    { num:84, word:"Component test", explain:"Tests individual parts of a larger software system.  ", phonetic:"[kəmˈpəʊ.nənt ˈtest]"},
    { num:85, word:"Compress", explain:"Reduce the size of a file to save space or to transmit it at a faster speed.", phonetic:"[kəmˈpres]"},
    { num:86, word:"Condition", explain:"Statement defining if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən]"},
    { num:87, word:"Conditional code", explain:"Code that executes based on specific conditions.", phonetic:"[kənˈdɪʃ.ən.əl kəʊd]"},
    { num:88, word:"Conditional statement", explain:"A statement that defines if a specific situation exists.", phonetic:"[kənˈdɪʃ.ən.əl ˈsteɪt.mənt]"},
    { num:89, word:"Connector", explain:"Links different parts of a system or program.", phonetic:"[kəˈnek.tər]"},
    { num:90, word:"Console", explain:"Text-based interface for interacting with a computer.", phonetic:"[kənˈsəʊl]"},
    { num:91, word:"Containers", explain:"Packaging of software with all its dependencies for easy deployment.", phonetic:"[kənˈteɪ.nərs]"},
    { num:92, word:"Continuous delivery", explain:"Automating the process of delivering software changes to a staging or production environment.", phonetic:"[kənˈtɪn.ju.əs dɪˈlɪv.ər.i]"},
    { num:93, word:"Continuous deployment", explain:"Automating the release and deployment of software changes to production.", phonetic:"[kənˈtɪn.ju.əs dɪˈplɔɪ.mənt]"},
    { num:94, word:"Continuous integration", explain:"The practice of regularly integrating code changes into a shared repository, ensuring early detection of integration issues in the development process.", phonetic:"[kənˈtɪn.ju.əs ˌɪn.tɪˈɡreɪ.ʃən]"},
    { num:95, word:"Cookies", explain:"Small files stored on a user's device by websites.", phonetic:"[ˈkʊk.is]"},
    { num:96, word:"CPU", explain:"Central processing unit, main brain of a computer.", phonetic:"[ˌsiː.piːˈjuː]"},
    { num:97, word:"Cross-browser compatibility", explain:"Ensuring that web applications function consistently across different web browsers.", phonetic:"[krɒs ˈbraʊ.zər kəmˌpæt.əˈbɪl.ə.ti]"},
    { num:98, word:"Cross-platform development", explain:"Creating software that can run on multiple operating systems or platforms.", phonetic:"[krɒs ˈplæt.fɔːm dɪˈvel.əp.mənt]"},
    { num:99, word:"CRUD", explain:"Create, Read, Update, Delete basic operations on data.", phonetic:"[krʌd]"},
    { num:100, word:"Cryptography", explain:"The study and application of techniques for secure communication and data protection.", phonetic:"[krɪpˈtɒɡ.rə.fi]"},
    { num:101, word:"Cyber Threat Intelligence", explain:"Information about potential cyber threats to inform decision-making and response.", phonetic:"[ˈsaɪ.bər θret ɪnˈtel.ɪ.dʒəns]"},
    { num:102, word:"Cybersecurity Frameworks", explain:"Comprehensive structures outlining best practices for managing cybersecurity risks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈfreɪm.wɜːks]"},
    { num:103, word:"Cybersecurity measures", explain:"Actions taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti ˈmeʒ.ərs]"},
    { num:104, word:"Cybersecurity", explain:"Measures taken to protect against cyberattacks.", phonetic:"[ˌsaɪ.bə.sɪˈkjʊə.rə.ti]"},

    { num:105, word:"Daemon", explain:"UNIX application that is permanently on alert on a server in order to perform certain tasks.", phonetic:"[ˈdiː.mən]"},
    { num:106, word:"Data analysis", explain:"Examining and interpreting data to extract meaningful insights.", phonetic:"[ˈdeɪ.tə əˈnæl.ə.sɪs]"},
    { num:107, word:"Data backup", explain:"Copying and storing data for recovery in case of loss.", phonetic:"[ˈdeɪ.tə ˈbæk.ʌp]"},
    { num:108, word:"Database", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs]"},
    { num:109, word:"Data center", explain:"Place to place large quantities of servers and communication equipment; It has all the facilities of bandwidth, physical security, 24-hour air conditioning, etc.", phonetic:"[ˈdeɪ.tə ˈsen.tər]"},
    { num:110, word:"Data integrity", explain:"Ensuring the accuracy and consistency of data throughout its lifecycle.", phonetic:"[ˈdeɪ.tə ɪnˈteɡ.rə.ti]"},
    { num:111, word:"Data privacy", explain:"Protecting the confidentiality and integrity of personal or sensitive information.", phonetic:"[ˈdeɪ.tə ˈprɪv.ə.si]"},
    { num:112, word:"Data shape", explain:"Structure of data, including its organization and types.", phonetic:"[ˈdeɪ.tə ʃeɪp]"},
    { num:113, word:"Data structure", explain:"The organization and types of data.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃər]"},
    { num:114, word:"Data structures", explain:"Organized formats for storing and managing data, such as arrays, lists, and trees.", phonetic:"[ˈdeɪ.tə ˈstrʌk.tʃərs]"},
    { num:115, word:"Database administrator (DBA)", explain:"Manages and maintains databases.", phonetic:"[ˈdeɪ.tə.beɪs ədˈmɪn.ɪ.streɪ.tər]"},
    { num:116, word:"Database management", explain:"Organized collection of data, usually accessed electronically.", phonetic:"[ˈdeɪ.tə.beɪs ˈmæn.ɪdʒ.mənt]"},
    { num:117, word:"DDL (data definition language)", explain:"A subset of SQL that defines and manages database structures.", phonetic:"[ˈdeɪ.tə ˌdef.ɪˈnɪʃ.ən ˈlæŋ.ɡwɪdʒ]"},
    { num:118, word:"DDoS", explain:"Distributed Denial of Service. It is an attack with a multitude of systems that have been 'hacked' directed at a particular target.", phonetic:"[ˈdiː.dɒs]"},
    { num:119, word:"Debugging breakpoint", explain:"Pausing program execution to identify and fix errors.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈbreɪkpɔɪnt]"},
    { num:120, word:"Debugging process", explain:"Finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ ˈprəʊ.ses]"},
    { num:121, word:"Debugging tools", explain:"Software tools used by developers to identify and fix errors or issues in their code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ tuːls]"},
    { num:122, word:"Debugging", explain:"Process of finding and fixing errors in software code.", phonetic:"[ˌdiːˈbʌ.ɡɪŋ]"},
    { num:123, word:"Decision", explain:"Choice made between different options.", phonetic:"[dɪˈsɪʒ.ən]"},
    { num:124, word:"Decision-making", explain:"The process of choosing between different options.", phonetic:"[dɪˈsɪʒ.ən ˈmeɪ.kɪŋ]"},
    { num:125, word:"Declaration", explain:"Specifies a variable, function, or other entity in code.", phonetic:"[ˌdek.ləˈreɪ.ʃən]"},
    { num:126, word:"Dependency Management", explain:"Handling and organizing the external libraries and components that a software project relies on.", phonetic:"[dɪˈpen.dən.si ˈmæn.ɪdʒ.mənt]"},
    { num:127, word:"Deployment", explain:"The process of releasing and installing a software application for use in a specific environment.", phonetic:"[dɪˈplɔɪ.mənt]"},
    { num:128, word:"Design patterns", explain:"Reusable solutions to common problems in software design, providing templates for solving issues in a flexible and efficient way.", phonetic:"[dɪˈzaɪn ˈpæt.əns]"},
    { num:129, word:"Designate", explain:"Assign or label something with a specific name or purpose.", phonetic:"[ˈdez.ɪɡ.neɪt]"},
    { num:130, word:"Development environment", explain:"The set of tools, processes, and configurations used by developers to write, test, and debug software.", phonetic:"[dɪˈvel.əp.mənt ɪnˈvaɪ.rə.mənt]"},
    { num:131, word:"Device", explain:"Electronic equipment with specific functions.", phonetic:"[dɪˈvaɪs]"},
    { num:132, word:"DevOps", explain:"Culture and practice of collaboration between development and operations teams.", phonetic:"[dɪv ɒps]"},
    { num:133, word:"DevSecOps", explain:"Integrating security practices into the DevOps (Development and Operations) process.", phonetic:"[dɪv sek ɒps]"},
    { num:134, word:"Disaster recovery planning", explain:"Developing strategies to recover IT systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i ˈplæn.ɪŋ]"},
    { num:135, word:"Disaster recovery", explain:"Planning and procedures for restoring and recovering systems after a catastrophic event.", phonetic:"[dɪˈzɑː.stər rɪˈkʌv.ər.i]"},
    { num:136, word:"Display", explain:"Screen or other device for showing visual information.", phonetic:"[dɪˈspleɪ]"},
    { num:137, word:"DJango", explain:"High-level web framework written in Python.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:138, word:"DML (data manipulation language)", explain:"A subset of SQL that manipulates and queries data within a database.", phonetic:"[ˈdeɪ.tə məˌnɪp.jəˈleɪ.ʃən ˈlæŋ.ɡwɪdʒ]"},
    { num:139, word:"Document", explain:"A file containing information, usually in electronic format.", phonetic:"[ˈdɒk.jə.mənt]"},
    { num:140, word:"Documentation", explain:"A set of documents that describe a system, software, or process.", phonetic:"[ˌdɒk.jə.menˈteɪ.ʃən]"},
    { num:141, word:"DOM", explain:"Document Object Model, a tree-like representation of the content of a web page.", phonetic:"[dɒm]"},
    { num:142, word:"Domain", explain:"A unique name that identifies a website on the internet.", phonetic:"[dəˈmeɪnʒ]"},
    { num:143, word:"Drag", explain:"To move an object on a touchscreen or with a mouse.", phonetic:"[dræɡ]"},

    { num:144, word:"Encryption", explain:"The process of converting information into a secure code to protect it from unauthorized access.", phonetic:"[ɪnˈkrip.ʃən]"},
    { num:145, word:"Error Handling", explain:"Managing and addressing errors that occur during the execution of a program.", phonetic:"[ˈer.ər ˈhænd.lɪŋ]"},
    { num:146, word:"Event", explain:"An action that occurs in a system or program.", phonetic:"[ɪˈvent]"},
    { num:147, word:"Exception Handling", explain:"The process of managing and responding to unexpected events or errors in software.", phonetic:"[ɪkˈsep.ʃən ˈhænd.lɪŋ]"},
    { num:148, word:"Extract", explain:"To obtain data from one source and store it in another location.", phonetic:"[ɪkˈstrækt]"},

    { num:149, word:"Firewall configuration", explain:"Setting up security measures to control incoming and outgoing network traffic.", phonetic:"[ˈfaɪə.wɔːl kənˌfɪɡ.əˈreɪ.ʃən]"},
    { num:150, word:"Flesh out", explain:"To expand or complete details of a plan or idea.", phonetic:"[fleʃ aʊt]"},
    { num:151, word:"Floppy disk", explain:"An outdated portable magnetic storage device.", phonetic:"[ˈflɒp.i dɪsk]"},
    { num:152, word:"Flowchart", explain:"A graphical representation of the steps in a process.", phonetic:"[ˈfləʊ.tʃɑːt]"},
    { num:153, word:"Fluid design", explain:"A web design that automatically adapts to different screen sizes.", phonetic:"[ˈfluː.ɪd dɪˈzaɪn]"},
    { num:154, word:"Framework", explain:"A set of tools and libraries for developing software.", phonetic:"[ˈfreɪm.wɜːk]"},
    { num:155, word:"Frameworks", explain:"Pre-built structures and tools that provide a foundation for developing software applications.", phonetic:"[ˈfreɪm.wɜːks]"},
    { num:156, word:"Frontend development", explain:"Creating the user interface and user experience components of a software application.", phonetic:"[ˌfrʌnt.end dɪˈvel.əp.mənt]"},
    { num:157, word:"Frontend", explain:"The part of a website or application that is visible and interactive for the user.", phonetic:"[ˌfrʌnt.end]"},
    { num:158, word:"Full-stack", explain:"Software development that encompasses both the frontend and backend.", phonetic:"[fʊl-stæk]"},
    { num:159, word:"Function", explain:"A block of code that performs a specific task.", phonetic:"[ˈfʌŋk.ʃən]"},
    { num:160, word:"Functional programming", explain:"A programming paradigm where computation is treated as the evaluation of mathematical functions, avoiding changing state and mutable data.", phonetic:"[ˈfʌŋk.ʃən.əl ˈprəʊ.ɡræm.ɪŋ]"},

    { num:161, word:"Git", explain:"A distributed version control system for tracking changes in code.", phonetic:"[ɡɪt]"},
    { num:162, word:"Github", explain:"A hosting platform for Git projects.", phonetic:"[ɡɪt hʌb]"},
    { num:163, word:"Gitlab", explain:"Similar to Github, a platform for hosting Git projects.", phonetic:"[ɡɪt læb]"},
    { num:164, word:"Go", explain:"A modern programming language developed by Google.", phonetic:"[ɡəʊ]"},

    { num:165, word:"Hacker", explain:"A person with computer skills who uses them for unauthorized purposes.", phonetic:"[ˈhæk.ər]"},
    { num:166, word:"Hacking", explain:"The attempt to gain unauthorized access to a computer system or network.", phonetic:"[ˈhæk.ɪŋ]"},
    { num:167, word:"Hard drive", explain:"A magnetic storage device that stores data on a spinning disk.", phonetic:"[hɑːd draɪv]"},
    { num:168, word:"Hardware", explain:"The physical components of a computer system.", phonetic:"[ˈhɑːd.weər]"},
    { num:169, word:"HDMI", explain:"High-Definition Multimedia Interface. It is a digital interface to transmit audio and video data on the same cable. Most HDTVs, DVDs, Blu-rays, cable boxes, and game consoles have HDMI support.", phonetic:"[ˌeɪtʃ.diː.emˈaɪ]"},
    { num:170, word:"Headphones", explain:"An audio device that is worn over the ears.", phonetic:"[ˈhed.fəʊnz]"},
    { num:171, word:"Highlight", explain:"To emphasize or make something more visible.", phonetic:"[ˈhaɪ.laɪt]"},
    { num:172, word:"Hosting", explain:"A service that provides space on a server to store web files.", phonetic:"[ˈhəʊstɪŋ]"},
    { num:173, word:"HTML", explain:"HyperText Markup Language defines the structure and content of web pages.", phonetic:"[ˌeɪtʃ.tiː.emˈel]"},
    { num:174, word:"HTTP", explain:"HyperText Transfer Protocol, the protocol for transferring data on the web.", phonetic:"[ˌeɪtʃ.tiː.tiːˈpiː]"},
    { num:175, word:"Hyperlink", explain:"A link in an electronic document that takes you to another location.", phonetic:"[ˈhaɪ.pə.lɪŋk]"},

    { num:176, word:"Iaas", explain:"Infrastructure as a Service, a cloud computing model that provides infrastructure as a service.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:177, word:"IDE", explain:"Integrated Development Environment, an environment for creating software.", phonetic:"[aɪˈdi]"},
    { num:178, word:"Incident management", explain:"The process of identifying, responding to, and resolving incidents or issues in a system.", phonetic:"[ˈɪn.sɪ.dənt ˈmæn.ɪdʒ.mənt]"},
    { num:179, word:"Incident response", explain:"Coordinated actions taken in response to a security incident or breach.", phonetic:"[ˈɪn.sɪ.dənt rɪˈspɒns]"},
    { num:180, word:"Infrastructure", explain:"The physical and virtual components that form the basis of a computer system.", phonetic:"[ˈɪn.frəˌstrʌk.tʃər]"},
    { num:181, word:"Input device", explain:"A device used to enter data into a computer system.", phonetic:"[ˈɪn.pʊt dɪˈvaɪs]"},
    { num:182, word:"Integration test", explain:"A test that verifies how different components of a system interact.", phonetic:"[ˌɪn.tɪˈɡreɪ.ʃən test]"},
    { num:183, word:"Internal storage", explain:"The storage space on an electronic device.", phonetic:"[ɪnˈtɜː.nəl ˈstɔː.rɪdʒ]"},
    { num:184, word:"Intrusion detection", explain:"Detecting and responding to unauthorized access or security breaches.", phonetic:"[ɪnˈtruː.ʒən dɪˈtek.ʃən]"},
    { num:185, word:"Involve", explain:"To include or make someone participate in something.", phonetic:"[ɪnˈvɒlv]"},
    
    { num:186, word:"Java", explain:"A general-purpose object-oriented programming language.", phonetic:"[ˈdʒɑː.və]"},
    { num:187, word:"JavaScript", explain:"A programming language that allows user interaction on web pages.", phonetic:"[ˈdʒɑː.və skrɪpt]"},
    { num:188, word:"JSON", explain:"A lightweight data-interchange format used for easy data exchange between applications.", phonetic:"[ˈd͡ʒeɪsən]"},

    { num:189, word:"Keyboard", explain:"An input device that allows you to type letters, numbers, and symbols.", phonetic:"[ˈkiː.bɔːd]"},

    { num:190, word:"Library", explain:"A collection of reusable code for performing specific tasks.", phonetic:"[ˈlaɪ.brər.i]"},
    { num:191, word:"Load balancing", explain:"Distributing network traffic evenly across multiple servers to ensure optimal performance.", phonetic:"[ləʊd ˈbæl.ən.sɪŋ]"},
    { num:192, word:"Load test", explain:"Tests that verify the performance of a system under load.", phonetic:"[ləʊd ˈtest]"},
    { num:193, word:"Log", explain:"A file that records events and activities in a system.", phonetic:"[lɒɡ]"},
    { num:194, word:"Logging", explain:"Recording events, activities, or errors in a system for analysis and troubleshooting.", phonetic:"[ˈlɒɡ.ɪŋ]"},
    { num:195, word:"Loops", explain:"Sections of code that execute repeatedly until a condition is met.", phonetic:"[luːps]"},
    
    { num:196, word:"Manual input", explain:"The process of entering data into a computer system manually.", phonetic:"[ˈmæn.ju.əl ˈɪn.pʊt]"},
    { num:197, word:"Manual operation", explain:"The process of performing a task in a computer system manually.", phonetic:"[ˈmæn.ju.əl ˌɒp.ərˈeɪ.ʃən]"},
    { num:198, word:"Merge", explain:"To integrate two or more things into one.", phonetic:"[mɜːdʒ]"},
    { num:199, word:"Microphone", explain:"A device that converts sound into an electrical signal.", phonetic:"[ˈmaɪ.krə.fəʊn]"},
    { num:200, word:"Microservices", explain:"An architectural style where an application is composed of small, independent services.", phonetic:"[ˈmaɪ.krə.sɜː.vɪs]"},
    { num:201, word:"Middleware", explain:"Software that acts as an intermediary between different software components.", phonetic:"[ˈmɪd.əl.weər]"},
    { num:202, word:"Mixin", explain:"A reusable piece of code that can be included in other classes.", phonetic:"[mɪksɪŋ]"},
    { num:203, word:"Mobile applications", explain:"Software designed to operate on mobile devices such as smartphones and tablets.", phonetic:"[ˈməʊ.baɪl ˌæp.lɪˈkeɪ.ʃəns]"},
    { num:204, word:"Mobile development", explain:"Creating apps for smartphones, tablets, and wearables.", phonetic:"[ˈməʊ.baɪl dɪˈvel.əp.mənt]"},
    { num:205, word:"Mobile OS", explain:"Operating system designed for mobile devices, e.g., Android.", phonetic:"[ˈməʊ.baɪl ɒs]"},
    { num:206, word:"Modem", explain:"Modulates/demodulates signals for communication.", phonetic:"[ˈməʊ.dem]"},
    { num:207, word:"Monitor", explain:"Display to visualize computer output.", phonetic:"[ˈmɒn.ɪ.tər]"},
    { num:208, word:"Monitoring", explain:"Continuously observing and measuring the performance and behavior of a system.", phonetic:"[ˈmɒn.ɪ.tə.rɪŋ]"},
    { num:209, word:"Monolith", explain:"Large application with all functionalities.", phonetic:"[ˈmɒn.ə.lɪθ]"},
    { num:210, word:"Mouse", explain:"Device to control the cursor on the screen.", phonetic:"[maʊs]"},
    { num:211, word:"MVP", explain:"Minimum viable product to validate an idea.", phonetic:"[ˌem.viːˈpiː]"},

    { num:212, word:"Network bandwidth", explain:"The amount of data that can be transmitted in a given time.", phonetic:"[ˈnet.wɜːk ˈbænd.wɪtθ]"},
    { num:213, word:"Network security", explain:"Protecting a computer network infrastructure against unauthorized access and attacks.", phonetic:"[ˈnet.wɜːk sɪˈkjʊə.rə.ti]"},
    { num:214, word:"NoSQL database", explain:"Stores data in a flexible format.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},

    { num:215, word:"Objective-C", explain:"Programming language for iOS and macOS.", phonetic:"[əbˈdʒek.tɪv siː]"},
    { num:216, word:"Object-Oriented programming (OOP)", explain:"A programming paradigm that uses objects, which encapsulate data and behavior, for software development.", phonetic:"[ˈɒb.dʒɪkt ˈɔː.ri.en.tɪd ˈprəʊ.ɡræm.ɪŋ]"},
    { num:217, word:"OEM", explain:"Original Equipment Manufacturer, it refers to companies that manufacture and package products for others, and also to companies that acquire a product or component and reuse it or incorporate it into another new product with their own brand.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:218, word:"Open source", explain:"Accessible and modifiable source code.", phonetic:"[ˈəʊ.pən sɔːs]"},
    { num:219, word:"Operators", explain:"Companies that provide telecommunications services.", phonetic:"[ˈɒp.ər.eɪ.tərs]"},
    { num:220, word:"Organization chart", explain:"A diagram that shows the hierarchical structure of an organization.", phonetic:"[ˌɔː.ɡən.aɪˈzeɪ.ʃən tʃɑːt]"},
    { num:221, word:"Outcome", explain:"Consequence of an action or process.", phonetic:"[ˈaʊt.kʌm]"},
    { num:222, word:"Output", explain:"Information or data produced by a system.", phonetic:"[ˈaʊt.pʊt]"},
    
    { num:223, word:"PaaS", explain:"Platform to develop, deploy, and manage applications.", phonetic:"[pɑːs]"},
    { num:224, word:"Penetration Testing", explain:"Simulating cyber-attacks to identify vulnerabilities and weaknesses in a system.", phonetic:"[ ˌpenɪˈtreɪʃən ˈtes.tɪŋ]"},
    { num:225, word:"Performance benchmark", explain:"Comparing the performance of different systems or software.", phonetic:"[pəˈfɔː.məns ˈbentʃ.mɑːk]"},
    { num:226, word:"Performance Monitoring", explain:"Tracking and analyzing the performance of a system during its operation.", phonetic:"[pəˈfɔː.məns ˈmɒn.ɪ.tər]"},
    { num:227, word:"Performance Optimization", explain:"Improving the efficiency and speed of a software application.", phonetic:"[pəˈfɔː.məns ˌɒp.tɪ.maɪˈzeɪ.ʃən]"},
    { num:228, word:"Performance Test", explain:"Performance measurement under real load.", phonetic:"[pəˈfɔː.məns test]"},
    { num:229, word:"Perl", explain:"Versatile language for web development and system administration.", phonetic:"[pɜːl]"},
    { num:230, word:"PHP", explain:"Language for developing dynamic web applications.", phonetic:"There isn't much information about the British phonetic of the word \n we will continue searching for our users"},
    { num:231, word:"Plugin", explain:"Module that adds functionalities to a program.", phonetic:"[ˈplʌɡ.ɪn]"},
    { num:232, word:"Plugs", explain:"Connectors to connect devices.", phonetic:"[plʌɡs]"},
    { num:233, word:"Port", explain:"Logical connection for communication between devices.", phonetic:"[pɔːt]"},
    { num:234, word:"Predefined process", explain:"A set of steps established beforehand to guide a particular action or task.", phonetic:"[ˌpriː.dɪˈfaɪnd ˈprəʊ.ses]"},
    { num:235, word:"Preparation", explain:"The act of getting ready for something, often involving gathering necessary materials and information.", phonetic:"[ˌprep.ərˈeɪ.ʃən]]"},
    { num:236, word:"Printed document", explain:"A physical copy of a document with text and/or images, created using a printer.", phonetic:"[ˈprɪn.tɪd ˈdɒk.jə.mənt]"},
    { num:237, word:"Printer", explain:"A device that produces printed documents from digital files.", phonetic:"[ˈprɪn.tər]"},
    { num:238, word:"Privilege management", explain:"Controlling and assigning specific privileges or permissions to users.", phonetic:"[ˈprɪv.əl.ɪdʒ]"},
];
export {glosary};